"use client";
/**
 * SignalCard — one row in the Prophet signal stream (left pane).
 *
 * Collapsed shows: ticker, BULL/BEAR badge, archetype tag, entry, days active,
 * live-vs-plan P&L (if last_price present), T1-progress bar, min-hold bar with
 * lock icon, phase chip.
 *
 * Expanded reveals: OptionCard sub-card.
 *
 * HONESTY DOCTRINE:
 *   - BULL/BEAR are engine-assigned direction labels — not recommendations.
 *   - Phase chip is descriptive lifecycle state.
 *   - P&L is live-vs-plan — labeled "vs plan" to avoid implying realized.
 *   - No "validated", no predictive copy.
 */

import { useState } from "react";
import { makeProphetT, phaseWhy } from "./prophetStrings";
import { OptionCard } from "./OptionCard";
import type { OptionContractPayload } from "./OptionCard";
import { Tip } from "@/components/ui/Tip";
import { pick } from "@/lib/finFormat";
import type { Lang } from "@/lib/i18n";

// ── Types ─────────────────────────────────────────────────────────────────────

export interface PlanSummary {
  id: string;
  asset: string;
  direction: "BULL" | "BEAR";
  /** signal archetype tag e.g. "Resumption", "Recovery" */
  archetype?: string | null;
  entry: number | null;
  targets: number[];
  invalidation: number | null;
  horizon_days: number | null;
  min_hold_days: number | null;
  /**
   * ISO date string for when the plan was issued.
   * Nested-shape payloads use `asof`; flat-shape payloads (current prod) use
   * `_signal_date`. Both are accepted — consumers should call planAsof(plan).
   */
  asof?: string | null;
  _signal_date?: string | null;
  option_contract: OptionContractPayload | null;
  /**
   * Nested management state (legacy shape).
   * Current flat shape hoists management_confidence / phase / recommended_action
   * to the plan top-level. Both shapes are accepted.
   */
  state?: {
    phase?: string | null;
    management_confidence?: number | null;
    recommended_action?: string | null;
    geometry?: {
      dist_to_stop_r?: number | null;
      dist_to_t1_r?:   number | null;
      horizon_pct_used?: number | null;
    } | null;
  } | null;
  /** Flat-shape: management confidence at top level (0–100) */
  management_confidence?: number | null;
  /** Flat-shape: lifecycle phase at top level */
  phase?: string | null;
  /** Flat-shape: recommended action at top level */
  recommended_action?: string | null;
  /** Last price from payload (optional — may be absent) */
  last_price?: number | null;
  /**
   * What-to-do-now bullets (optional — generated by content engine).
   * List of 2-3 numbered action strings keyed to current phase.
   * Graceful fallback: block hidden when absent.
   */
  what_to_do_now?: string[] | null;
  /** ZH variant of what_to_do_now (optional — present when engine emits zh blocks). */
  what_to_do_now_zh?: string[] | null;
  /**
   * Profit-taking plan rows (optional — generated by content engine).
   * Each row: {level: number|null, label: string, action: string, status: "ACTIVE"|"PENDING"|"DONE"}
   * Graceful fallback: block hidden when absent.
   */
  profit_plan?: Array<{
    level: number | null;
    label: string;
    action: string;
    status: "ACTIVE" | "PENDING" | "DONE";
  }> | null;
  /** ZH variant of profit_plan rows (same shape, zh action strings). */
  profit_plan_zh?: Array<{
    level: number | null;
    label: string;
    action: string;
    status: "ACTIVE" | "PENDING" | "DONE";
  }> | null;
  /** Structured producer-owned entry band. Terminal displays it; it never re-derives it. */
  entry_zone?: {
    low?: number | null;
    high?: number | null;
    chase_above?: number | null;
    zone_class?: string | null;
    stance?: string | null;
    basis?: string | null;
    basis_zh?: string | null;
  } | null;
  /** Nightly state of that band. Only a still-live band is drawn as a current opportunity box. */
  entry_zone_state?: {
    state?: string | null;
    stance?: string | null;
    sessions_remaining?: number | null;
  } | null;
  /**
   * Machine tag for how the plan was originated, e.g. "outage_backfill_2026_08_09".
   * Present only on reconstructed rows — it exists so the cohort can be filtered, and
   * is never rendered: the internal name of the event is not reader-facing copy.
   */
  origination_mode?: string | null;
  /**
   * Reconstruction disclosure, present only on a plan the macro builder rebuilt after
   * an outage instead of originating live. Absent on every live plan, which is what
   * makes a card without it render exactly as it did before this shipped.
   */
  origination_note?: OriginationNote | null;
}

/**
 * FINISHED bilingual copy, shipped on the row by the producer
 * (macro `engine/prophet_bridge.py`), not a key to look up.
 *
 * Both surfaces that draw these plans — the dashboard board and this Terminal — read
 * the same strings off the same row precisely so the wording cannot drift between
 * them. `tip_*` is optional: a row whose origination date will not parse ships the
 * chip with no receipt rather than a receipt with a blank day.
 */
export interface OriginationNote {
  /** Tier 1 chip copy, English. */
  en: string;
  /** Tier 1 chip copy, Chinese. */
  zh: string;
  /** Tier 2 receipt, English — absent when the producer could not date the row. */
  tip_en?: string | null;
  /** Tier 2 receipt, Chinese — absent when the producer could not date the row. */
  tip_zh?: string | null;
  date_en?: string | null;
  date_zh?: string | null;
}

/** Return ISO date string from either flat (_signal_date) or nested (asof) shape. */
export function planAsof(plan: PlanSummary): string {
  return plan._signal_date ?? plan.asof ?? "";
}

/** Return management_confidence from either flat or nested shape. */
export function planConfidence(plan: PlanSummary): number | null {
  return plan.management_confidence ?? plan.state?.management_confidence ?? null;
}

/** Return lifecycle phase from either flat or nested shape. */
export function planPhase(plan: PlanSummary): string | null {
  return plan.phase ?? plan.state?.phase ?? null;
}

/** Return recommended_action from either flat or nested shape. */
export function planRecommendedAction(plan: PlanSummary): string | null {
  return plan.recommended_action ?? plan.state?.recommended_action ?? null;
}

/**
 * The row's reconstruction disclosure in the reader's language — chip (Tier 1) plus
 * receipt (Tier 2) — or `null` when the plan was originated live.
 *
 * EVERY STRING IS THE ROW'S OWN. This repo words none of it and must never start:
 * the producer ships finished EN/ZH copy on the row so the dashboard and the Terminal
 * cannot say different things about the same plan. That is also why there is no
 * `prophetStrings` key here — a key each surface words for itself is the second place
 * for the wording to drift.
 *
 * Fail-soft on the receipt, exactly as the producer is: no tip means chip only, never
 * a chip promising a hover that has nothing behind it.
 */
export function planOriginationNote(
  plan: PlanSummary,
  lang: Lang,
): { chip: string; tip: string | null } | null {
  const note = plan.origination_note;
  if (!note) return null;
  const chip = lang === "zh" ? note.zh : note.en;
  if (!chip) return null;
  return { chip, tip: (lang === "zh" ? note.tip_zh : note.tip_en) || null };
}

interface SignalCardProps {
  plan: PlanSummary;
  lang: Lang;
  selected: boolean;
  onSelect: (plan: PlanSummary) => void;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function daysActive(asof: string): number {
  const issued = new Date(asof).getTime();
  // Math.max(0, NaN) === NaN — guard explicitly so a missing/invalid date
  // never propagates NaN into the rendered string.
  if (!Number.isFinite(issued)) return 0;
  const now = Date.now();
  return Math.max(0, Math.floor((now - issued) / 86_400_000));
}

function t1Progress(entry: number | null, t1: number | null, last: number | null, isBear: boolean): number | null {
  if (entry == null || t1 == null || last == null) return null;
  if (isBear) {
    // BEAR: progress is downward (entry→t1 = entry−t1 total; entry−last = so far)
    const total = entry - t1;
    const done  = entry - last;
    if (total <= 0) return null;
    return Math.max(0, Math.min(100, (done / total) * 100));
  }
  const total = t1 - entry;
  const done  = last - entry;
  if (total <= 0) return null;
  return Math.max(0, Math.min(100, (done / total) * 100));
}

/** One token per archetype — `.obs-tag` derives fill and ring from it. */
function archetypeColor(tag: string): string {
  const t = tag.toLowerCase();
  if (t === "resumption") return "var(--warn)";
  if (t === "recovery")   return "var(--brand-2)";
  if (t === "breakout")   return "var(--ai)";
  return "var(--muted)";
}

/**
 * Lifecycle-phase tint, shared by every Prophet surface that shows a phase chip
 * (this card, the analysis header, the confidence panel) so one state never wears
 * three colours. Directional states ride --up/--down and flip with data-updown.
 *
 *   pre_trigger      → muted     (armed, nothing has happened)
 *   triggered_pre_t1 → brand-2   (live, working)
 *   at_t1/T1→T2/T2   → up        (at or past target)
 *   overtime         → warn      (window elapsed, price frame stale — caution, not direction)
 *   invalidated      → down      (thesis broken)
 */
export function phaseTone(phase: string | null | undefined): string {
  if (!phase) return "var(--text-2)";
  if (phase === "invalidated") return "var(--down)";
  if (phase === "overtime") return "var(--warn)";
  if (phase.includes("t1") || phase.includes("t2")) {
    return phase === "triggered_pre_t1" ? "var(--brand-2)" : "var(--up)";
  }
  if (phase === "pre_trigger") return "var(--muted)";
  return "var(--text-2)";
}

function entryZoneView(plan: PlanSummary, lang: Lang): {
  range: string;
  stance: string;
  chase: string | null;
  window: string | null;
  aria: string | undefined;
  color: string;
} | null {
  const zone = plan.entry_zone;
  const state = plan.entry_zone_state;
  // A converted zone is an expired band that the move skipped; it may license a
  // starter elsewhere, but its old prices are not a current opportunity box.
  // Likewise, once management has advanced to HOLD/TRAIL/INVALIDATED, a still-live
  // unfilled band is historical entry context, not the user's current action.
  if (!zone || !state || state.state !== "live") return null;
  if (planRecommendedAction(plan) !== "wait") return null;
  if (zone.high == null || !Number.isFinite(zone.high)) return null;

  const low = zone.low != null && Number.isFinite(zone.low) ? zone.low : zone.high;
  const range = `$${low.toFixed(2)}–$${zone.high.toFixed(2)}`;
  const rawStance = state.stance ?? zone.stance ?? "wait";
  const stanceMap: Record<string, [string, string]> = {
    wait: ["Wait", "等待"],
    starter: ["Starter", "试探仓"],
    accumulate: ["Accumulate", "分批建仓"],
  };
  const stancePair = stanceMap[rawStance] ?? [rawStance, rawStance];
  const stance = pick(lang === "zh", stancePair[0], stancePair[1]);
  const chase = zone.chase_above != null && Number.isFinite(zone.chase_above)
    ? `${pick(lang === "zh", "No chase", "不追高")} > $${zone.chase_above.toFixed(2)}`
    : null;
  const remaining = state.sessions_remaining;
  const window = remaining != null && Number.isFinite(remaining) && remaining >= 0
    ? pick(lang === "zh", `${remaining} sessions left`, `剩余 ${remaining} 个交易日`)
    : null;
  const aria = (lang === "zh" ? zone.basis_zh : zone.basis) ?? undefined;
  const color = rawStance === "accumulate" ? "var(--up)"
    : rawStance === "starter" ? "var(--brand-2)" : "var(--warn)";
  return { range, stance, chase, window, aria, color };
}

// ── Component ──────────────────────────────────────────────────────────────────

export function SignalCard({ plan, lang, selected, onSelect }: SignalCardProps) {
  const t = makeProphetT(lang);
  const [expanded, setExpanded] = useState(false);

  const isBear  = plan.direction === "BEAR";
  const t1      = plan.targets?.[0] ?? null;
  const days    = daysActive(planAsof(plan));
  const t1pct   = t1Progress(plan.entry, t1, plan.last_price ?? null, isBear);

  // Min-hold bar
  const minHold = plan.min_hold_days ?? null;
  const minPct  = minHold != null && minHold > 0
    ? Math.min(100, (days / minHold) * 100)
    : null;
  const isLocked    = minPct != null && minPct < 100;
  const holdLabel   = isLocked ? t("locked") : t("eligible");
  const holdColor   = isLocked ? "var(--muted)" : "var(--up)";

  // P&L vs plan
  let pnlPct: number | null = null;
  if (plan.last_price != null && plan.entry != null && plan.entry > 0) {
    const raw = (plan.last_price - plan.entry) / plan.entry * 100;
    pnlPct = isBear ? -raw : raw;
  }

  // Phase chip — supports both flat (plan.phase) and nested (plan.state?.phase) shapes
  const currentPhase = planPhase(plan);
  const phaseMap: Record<string, string> = {
    pre_trigger:       t("phasePretrigger"),
    triggered_pre_t1:  t("phaseTriggered"),
    at_t1:             t("phaseAtT1"),
    between_t1_t2:     t("phaseBetweenT1T2"),
    at_t2:             t("phaseAtT2"),
    overtime:          t("phaseOvertime"),
    invalidated:       t("phaseInvalidated"),
  };
  const phaseDisplay = currentPhase ? (phaseMap[currentPhase] ?? currentPhase) : null;
  const isInvalidated = currentPhase === "invalidated";
  const phaseColor = phaseTone(currentPhase);
  // null for every phase but `overtime`, so React omits the attribute and the card
  // renders byte-identically for a fresh plan.
  const phaseNote = phaseWhy(lang, currentPhase);

  const dirColor = isBear ? "var(--down)" : "var(--up)";

  // Reconstruction disclosure — null for every live plan, which is every plan today.
  const origination = planOriginationNote(plan, lang);

  // Producer-owned structured opportunity band. Hide historical filled/expired bands:
  // the compact card answers "where could I act now?", while the detail plan keeps history.
  const entryZone = entryZoneView(plan, lang);

  return (
    <div
      className={`obs-card obs-prophet-signal${selected ? " sel" : ""}`}
      style={{
        ...CARD_STYLE,
        opacity: isInvalidated ? 0.6 : 1,
      }}
      onClick={() => onSelect(plan)}
      role="option"
      aria-selected={selected}
    >
      {/* Row 1: ticker + direction + archetype + phase */}
      <div style={ROW}>
        <span style={TICKER_STYLE}>{plan.asset}</span>

        {/* Direction badge */}
        <span
          className="obs-tag"
          style={{ ...CHIP_BASE, "--c": dirColor, fontWeight: 700 } as React.CSSProperties}
        >
          {isBear ? `▼ ${t("bear")}` : `▲ ${t("bull")}`}
        </span>

        {/* Archetype tag */}
        {plan.archetype && (
          <span
            className="obs-tag"
            style={{ ...CHIP_BASE, "--c": archetypeColor(plan.archetype) } as React.CSSProperties}
          >
            {plan.archetype}
          </span>
        )}

        {/* Spacer */}
        <div style={{ flex: 1 }} />

        {/* Phase chip — lifecycle state, tinted by phaseTone() */}
        {phaseDisplay && (
          <span
            className="obs-tag"
            style={{ ...CHIP_BASE, "--c": phaseColor, fontSize: 9 } as React.CSSProperties}
            aria-label={phaseNote ?? undefined}
          >
            {phaseDisplay}
          </span>
        )}
      </div>

      {/* Row 2: entry / days / P&L */}
      <div style={{ ...ROW, marginTop: 6, gap: 12, fontSize: 10.5 }}>
        <span style={FACT}>
          <span className="obs-lbl" style={FACT_LABEL}>
            {entryZone ? pick(lang === "zh", "Plan anchor", "计划锚点") : t("entryLabel")}
          </span>
          <span className="num" style={FACT_VAL}>{plan.entry != null ? `$${plan.entry.toFixed(2)}` : "—"}</span>
        </span>
        <span style={FACT}>
          <span style={FACT_LABEL}></span>
          <span className="num" style={{ ...FACT_VAL, color: "var(--muted)" }}>{days}{t("daysActive")}</span>
        </span>
        {pnlPct != null && (
          <span className="num" style={{ marginLeft: "auto", font: "600 11px/1 var(--font-num)", fontVariantNumeric: "tabular-nums", color: pnlPct >= 0 ? "var(--up)" : "var(--down)" }}>
            {pnlPct >= 0 ? "+" : ""}{pnlPct.toFixed(1)}%
            <span style={{ font: "500 9px/1 var(--font-ui)", color: "var(--muted)", marginLeft: 3 }}>
              {t("vsPlan")}
            </span>
          </span>
        )}
      </div>

      {/* Current producer-owned action band: compact enough to scan in the stream. */}
      {entryZone && (
        <div
          className="obs-prophet-entry-zone"
          style={ENTRY_ZONE}
          aria-label={entryZone.aria
            ? `${pick(lang === "zh", "Opportunity box", "机会区间")}. ${entryZone.aria}`
            : pick(lang === "zh", "Opportunity box", "机会区间")}
        >
          <div style={ENTRY_ZONE_TOP}>
            <span style={ENTRY_ZONE_LABEL}>{pick(lang === "zh", "Opportunity box", "机会区间")}</span>
            <span
              className="obs-tag"
              style={{ ...ENTRY_ZONE_STANCE, "--c": entryZone.color } as React.CSSProperties}
            >
              {entryZone.stance}
            </span>
          </div>
          <div style={ENTRY_ZONE_MAIN}>
            <span className="num" style={ENTRY_ZONE_RANGE}>{entryZone.range}</span>
            {(entryZone.chase || entryZone.window) && (
              <span style={ENTRY_ZONE_META}>
                {[entryZone.chase, entryZone.window].filter(Boolean).join(" · ")}
              </span>
            )}
          </div>
        </div>
      )}

      {/* T1 progress bar */}
      {t1pct != null && (
        <div style={{ marginTop: 7 }}>
          <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 3 }}>
            <span className="num" style={{ font: "500 9.5px/1 var(--font-ui)", fontVariantNumeric: "tabular-nums", color: "var(--muted)" }}>{t1pct.toFixed(0)}% {t("t1Progress")}</span>
          </div>
          <div style={PROGRESS_TRACK}>
            <div
              style={{
                height: "100%",
                width: `${t1pct}%`,
                background: "var(--up)",
                borderRadius: "var(--r-pill)",
                transition: "width .3s",
              }}
            />
          </div>
        </div>
      )}

      {/* Min-hold bar */}
      {minPct != null && (
        <div style={{ marginTop: 5 }}>
          <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 3, alignItems: "center" }}>
            <span className="num" style={{ font: "500 9.5px/1 var(--font-ui)", fontVariantNumeric: "tabular-nums", color: "var(--muted)" }}>
              {days}d / {minHold}d {t("minHold")}
            </span>
            <span style={{ font: "600 9px/1 var(--font-ui)", color: holdColor }}>
              {isLocked ? "🔒 " : ""}{holdLabel}
            </span>
          </div>
          <div style={PROGRESS_TRACK}>
            <div
              style={{
                height: "100%",
                width: `${minPct}%`,
                background: isLocked ? "var(--line-3)" : "var(--up)",
                borderRadius: "var(--r-pill)",
                transition: "width .3s",
              }}
            />
          </div>
        </div>
      )}

      {/*
        Reconstruction disclosure — provenance, never stance.

        LAST on purpose, and the quietest chip on the card. How a pick was originated
        does not change what to do about it today, so it must not compete with the
        direction badge or the phase chip above it; a reader scanning the stream gets
        the plan first and this accounting after. Same reasoning, and the same "quiet
        clause, receipt one hover away" shape, as the dashboard board's own footnote.

        `--c: var(--muted)` is the card's neutral token — `.obs-tag` derives both the
        12% fill and the 30% ring from it, so this reads as a fact and not as an alarm.
        It is deliberately NOT --warn: nothing is wrong with the stock. Naming only the
        token (never a literal colour) is also what keeps it correct if the Terminal
        ever stops being dark-only — see app/settings.css on why there is one theme.

        The chip WRAPS rather than truncating. It is a disclosure, so a narrow pane may
        cost it a second line but must never cost it half a sentence.
      */}
      {origination && (
        <div style={{ ...ORIGINATION_ROW, paddingRight: plan.option_contract ? 22 : 0 }}>
          {origination.tip ? (
            <Tip label={origination.tip} size="card">
              <span className="obs-tag" style={ORIGINATION_CHIP_TIP} tabIndex={0}>
                {origination.chip}
              </span>
            </Tip>
          ) : (
            <span className="obs-tag" style={ORIGINATION_CHIP}>
              {origination.chip}
            </span>
          )}
        </div>
      )}

      {/* Expand toggle for OptionCard */}
      {plan.option_contract && (
        <button
          style={EXPAND_BTN}
          onClick={(e) => { e.stopPropagation(); setExpanded((v) => !v); }}
          aria-expanded={expanded}
          aria-label={expanded ? t("optionCollapse") : t("optionExpand")}
        >
          {expanded ? "▲" : "▼"}
        </button>
      )}

      {/* OptionCard sub-card (expanded) */}
      {expanded && plan.option_contract && (
        <OptionCard contract={plan.option_contract} lang={lang} />
      )}
    </div>
  );
}

// ── Style constants ───────────────────────────────────────────────────────────

const CARD_STYLE: React.CSSProperties = {
  position: "relative",
  padding: "12px 13px",
  cursor: "pointer",
  marginBottom: 8,
};

const ROW: React.CSSProperties = {
  display: "flex",
  alignItems: "center",
  flexWrap: "wrap",
  gap: 5,
};

const TICKER_STYLE: React.CSSProperties = {
  font: "750 15px/1 var(--font-ui)",
  color: "var(--text)",
  letterSpacing: ".01em",
};

/** Dense overrides for `.obs-tag` in the card's chip row; the tint rides `--c`. */
const CHIP_BASE: React.CSSProperties = {
  fontSize: 10,
  fontWeight: 600,
  padding: "3px 8px",
  gap: 3,
};

const ENTRY_ZONE: React.CSSProperties = {
  marginTop: 8,
  padding: "8px 9px",
  border: "1px solid var(--line-2)",
  borderRadius: "var(--r-md)",
  background: "color-mix(in srgb,var(--panel) 76%,var(--bg))",
};

const ENTRY_ZONE_TOP: React.CSSProperties = {
  display: "flex",
  alignItems: "center",
  justifyContent: "space-between",
  gap: 8,
};

const ENTRY_ZONE_LABEL: React.CSSProperties = {
  font: "650 9px/1 var(--font-ui)",
  color: "var(--muted)",
  letterSpacing: ".055em",
  textTransform: "uppercase",
};

const ENTRY_ZONE_STANCE: React.CSSProperties = {
  ...CHIP_BASE,
  fontSize: 9,
  padding: "2px 7px",
};

const ENTRY_ZONE_MAIN: React.CSSProperties = {
  display: "flex",
  alignItems: "baseline",
  flexWrap: "wrap",
  gap: "4px 9px",
  marginTop: 5,
};

const ENTRY_ZONE_RANGE: React.CSSProperties = {
  font: "700 13px/1 var(--font-num)",
  fontVariantNumeric: "tabular-nums",
  color: "var(--text)",
};

const ENTRY_ZONE_META: React.CSSProperties = {
  font: "500 9px/1.3 var(--font-ui)",
  color: "var(--text-2)",
};

const ORIGINATION_ROW: React.CSSProperties = {
  display: "flex",
  marginTop: 8,
};

/**
 * Subordinate by every lever the card has: the neutral token, the smallest chip size
 * already in use here (the phase chip's 9px), and normal rather than semibold weight.
 * `lineHeight` is set because `.obs-tag` ships `/1` for a chip that never wraps, and
 * this one may.
 */
const ORIGINATION_CHIP: React.CSSProperties = {
  ...CHIP_BASE,
  "--c": "var(--muted)",
  fontSize: 9,
  fontWeight: 500,
  lineHeight: 1.35,
  whiteSpace: "normal",
  textAlign: "left",
} as React.CSSProperties;

/** Same chip, plus the house "there is a receipt here" affordance. */
const ORIGINATION_CHIP_TIP: React.CSSProperties = {
  ...ORIGINATION_CHIP,
  cursor: "help",
  outline: "none",
};

const FACT: React.CSSProperties = {
  display: "flex",
  flexDirection: "column",
  gap: 2,
};

const FACT_LABEL: React.CSSProperties = {
  font: "500 9px/1 var(--font-ui)",
  color: "var(--muted)",
};

const FACT_VAL: React.CSSProperties = {
  font: "600 11px/1 var(--font-num)",
  fontVariantNumeric: "tabular-nums",
  color: "var(--text)",
};

const PROGRESS_TRACK: React.CSSProperties = {
  height: 4,
  background: "var(--line-2)",
  borderRadius: "var(--r-pill)",
  overflow: "hidden",
};

const EXPAND_BTN: React.CSSProperties = {
  position: "absolute",
  bottom: 6,
  right: 8,
  font: "600 8px/1 var(--font-ui)",
  color: "var(--muted)",
  background: "none",
  border: "none",
  cursor: "pointer",
  padding: "2px 4px",
};
