import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { expiryPnl, expiryReference, shiftedIv, shockedSpot, syntheticPlan, type ReferencePlan } from '../../../terminal/lib/optionsPlanReference';
import { fmtTick, niceTicks, padDomain, thinLabels, useChartWidth } from '../../../terminal/components/charts/svgChart';
type View = 'plan' | 'scenario' | 'watch' | 'review';
type Copy = (en: string, zh: string) => string;
const dollars = (value: string | number, digits = 2) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', minimumFractionDigits: digits, maximumFractionDigits: digits }).format(Number(value));
const exactPrice = (value: string) => dollars(value, Math.max(2, (value.split('.')[1] || '').length));
const plus = (n: number) => n > 0 ? `+${n}` : `${n}`;
function Payoff({ plan, spot, t }: {
    plan: ReferencePlan;
    spot: string;
    t: Copy;
}) {
    const ref = useRef<HTMLDivElement>(null), width = useChartWidth(ref), height = 230;
    const prices = [170, 180, 185, 187, 190, 195, 200], values = prices.map(p => Number(expiryPnl(plan, String(p)).gross));
    const [lo, hi] = padDomain(Math.min(...values), Math.max(...values), { includeZero: true, padFrac: .2 });
    const x = (v: number) => 48 + (v - 170) / 30 * (width - 68), y = (v: number) => 16 + (hi - v) / (hi - lo) * (height - 54);
    const yt = niceTicks(lo, hi, 3), xt = niceTicks(170, 200, 6);
    return <div className="chart" ref={ref}>
    <svg role="img" aria-label={t('Gross payoff at expiration, not a pre-expiry valuation', '到期毛损益，不代表到期前估值')} width={width} height={height} viewBox={`0 0 ${width} ${height}`}>
      {yt.values.map(v => <g key={v}><line className="grid" x1="48" x2={width - 20} y1={y(v)} y2={y(v)}/><text x="38" y={y(v) + 4} textAnchor="end">{fmtTick(v, yt.step)}</text></g>)}
      {thinLabels(xt.values, x, 52).map(v => <text key={v} x={x(v)} y={height - 12} textAnchor="middle">{fmtTick(v, xt.step)}</text>)}
      <path className="payoff" d={prices.map((p, i) => `${i ? 'L' : 'M'}${x(p)},${y(values[i])}`).join(' ')}/>
      {Number(spot) >= 170 && Number(spot) <= 200 && <circle className="dot" r="5" cx={x(Number(spot))} cy={y(Number(expiryPnl(plan, spot).gross))}/>}
    </svg>
  </div>;
}
function Choices({ values, selected, onChange, label, format = String }: {
    values: number[];
    selected: number;
    onChange: (v: number) => void;
    label: string;
    format?: (v: number) => string;
}) {
    return <div className="choices" role="group" aria-label={label}>{values.map(v => <button key={v} aria-pressed={selected === v} onClick={() => onChange(v)}>{format(v)}</button>)}</div>;
}
function App() {
    const [view, setView] = useState<View>('plan'), [lang, setLang] = useState<'en' | 'zh'>('en'), [theme, setTheme] = useState('dark');
    const [basis, setBasis] = useState<ReferencePlan['basis']>('midpoint'), [custom, setCustom] = useState('2.05'), [quantity, setQuantity] = useState('1');
    const [shock, setShock] = useState(2), [sessions, setSessions] = useState(1), [iv, setIv] = useState(5);
    const modal = useRef<HTMLDialogElement>(null), heading = useRef<HTMLHeadingElement>(null), initial = useRef(true);
    const t: Copy = (en, zh) => lang === 'en' ? en : zh;
    const plan = syntheticPlan();
    plan.basis = basis;
    plan.customDebit = custom;
    plan.legs[0].quantity = Number(quantity);
    plan.legs[1].quantity = -Number(quantity);
    let result: ReturnType<typeof expiryReference> | null = null;
    try {
        result = expiryReference(plan);
    }
    catch { /* Invalid edits stay visible and suppress all derived values. */ }
    const spot = shockedSpot('182.40', shock);
    useEffect(() => { document.documentElement.lang = lang === 'en' ? 'en' : 'zh-Hans'; document.documentElement.dataset.lang = lang; }, [lang]);
    useEffect(() => { document.documentElement.dataset.theme = theme; }, [theme]);
    useEffect(() => { if (initial.current) {
        initial.current = false;
        return;
    } heading.current?.focus(); window.scrollTo(0, 0); }, [view]);
    const names: Record<View, string> = { plan: t('Plan', '计划'), scenario: t('Scenarios', '情景'), watch: t('Save & watch', '保存与观察'), review: t('Review', '复盘') };
    const title: Record<View, string> = { plan: t('Give the idea an expression', '为研究选择合约'), scenario: t('Explore before expiry', '探索到期前情景'), watch: t('Preserve the idea. Define the next check.', '保留研究，定义下一次观察。'), review: t('What changed since your plan?', '计划之后，什么发生了变化？') };
    const subtitle: Record<View, string> = { plan: t('Choose exact contracts and understand the price you are comparing.', '选择明确合约，了解价格比较的依据。'), scenario: t('Change an assumption. See what can be priced.', '调整假设，查看哪些结果可以估值。'), watch: t('Research, a watch draft and an armed alert are separate states.', '研究记录、观察草稿与已启用提醒是不同状态。'), review: t('Original evidence stays intact. New evidence is shown beside it.', '原始证据保持不变，新证据并列呈现。') };
    function exportExample() {
        if (!result)
            return;
        const blob = new Blob([JSON.stringify({ schema: 'options.plan_interaction_example/v1', synthetic: true, savedResearch: false, plan, expiryReference: result, scenario: { shockPercent: shock, spot, elapsedSessions: sessions, ivShiftPercentagePoints: iv, valuationAt: null, preExpiryValue: null }, watch: { state: 'unsaved_draft', armed: false }, productionAcceptance: false }, null, 2)], { type: 'application/json' });
        const url = URL.createObjectURL(blob), a = document.createElement('a');
        a.href = url;
        a.download = 'NVDA-synthetic-plan-example.json';
        a.click();
        setTimeout(() => URL.revokeObjectURL(url), 1000);
    }
    const metrics = result && <div className="metrics"><div><span className="label">{t('Maximum loss', '最大亏损')}</span><strong data-testid="max-loss">{dollars(result.grossMaxLoss)}</strong></div><div><span className="label">{t('Maximum gain', '最大收益')}</span><strong data-testid="max-gain">{dollars(result.grossMaxGain)}</strong></div><div><span className="label">{t('Break-even', '盈亏平衡')}</span><strong data-testid="break-even">{exactPrice(result.breakEven)}</strong></div></div>;
    const invalid = !result && <div role="alert" className="error">{t('Enter 1–10,000 spreads and a debit greater than $0 and below $5, with at most four decimal places.', '请输入 1–10,000 组价差；每股净支出须大于 $0 且小于 $5，最多四位小数。')}</div>;
    return <>
    <header className="host"><strong>{t('Options · interactive design review', '期权 · 交互设计评审')}</strong><small>{t('Synthetic example · no connected account', '合成示例 · 未连接账户')}</small><div className="tools"><button onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')} aria-label={t('Switch theme', '切换主题')}>{theme === 'dark' ? t('Light', '浅色') : t('Dark', '深色')}</button><button onClick={() => setLang(lang === 'en' ? 'zh' : 'en')} aria-label={t('Switch language', '切换语言')}>{lang === 'en' ? '中文' : 'English'}</button></div></header>
    <nav className="tasknav" aria-label={t('Example steps', '示例步骤')}>{(Object.keys(names) as View[]).map((v, i) => <button key={v} data-testid={`nav-${v}`} aria-current={view === v ? 'step' : undefined} onClick={() => setView(v)}><span>{i + 1}</span>{names[v]}</button>)}</nav>
    <main><div className="intro"><h1 ref={heading} tabIndex={-1}>{title[view]}</h1><p>{subtitle[view]}</p><div className="contract">{t('NVDA · Oct 16, 2026 · +1 185 call / −1 190 call · ×100 per contract', 'NVDA · 2026年10月16日 · +1 185 看涨 / −1 190 看涨 · 每张 ×100')}</div></div>
    {view === 'plan' && <div className="layout plan"><div className="stack">
      <section className="panel"><h2>{t('Selected legs', '已选合约')}</h2><div className="stack">{plan.legs.map((l, i) => <div className="selected-leg" key={l.strike}><div className="row"><strong>{i === 0 ? t('Buy 185 call', '买入 185 看涨') : t('Sell 190 call', '卖出 190 看涨')}</strong><span className="pill">{i === 0 ? '+' : '−'}{quantity || '—'}</span></div><div className="row"><span>{t('Bid / ask', '买价 / 卖价')}</span><span className="value">{l.bid} / {l.ask}</span></div></div>)}</div><label className="fieldrow">{t('Spread quantity', '价差组数')}<input aria-label={t('Spread quantity', '价差组数')} value={quantity} type="number" min="1" max="10000" step="1" onChange={e => setQuantity(e.target.value)}/></label><small className="help">{t('Standard shares, physical settlement, American exercise. Corporate actions and dividends still need checking.', '标准股票交割、美式行权。仍需核对公司行动与股息。')}</small></section>
      <section className="panel"><h2>{t('Contract comparison', '合约比较')}</h2><p>{t('Synthetic quote snapshot · Sep 25, 10:42 ET', '合成报价快照 · 9月25日 10:42 美东时间')}</p><table className="chain"><thead><tr>{[t('Call', '看涨'), t('Bid', '买价'), t('Ask', '卖价'), 'IV', t('Volume', '成交量'), t('OI · Sep 24', '持仓量 · 9月24日')].map(v => <th key={v}>{v}</th>)}</tr></thead><tbody>{[['185', '5.20', '5.30', '35.8%', '4,920', '18,420'], ['190', '3.20', '3.30', '34.8%', '3,760', '22,810']].map(r => <tr key={r[0]}>{r.map((v, i) => <td key={i} data-label={[t('Strike', '行权价'), t('Bid', '买价'), t('Ask', '卖价'), 'IV', t('Volume', '成交量'), t('Dated OI', '有日期的持仓量')][i]}>{v}</td>)}</tr>)}</tbody></table><small className="help">{t('Example rows only; this is not a live chain or a contract-search tool. OI is dated separately from the quote.', '仅为示例行，并非实时期权链或合约搜索工具。持仓量日期与报价日期分别标示。')}</small></section>
    </div><section className="panel risk"><h2>{t('Price & expiry risk', '价格与到期风险')}</h2><div className="choices" role="group" aria-label={t('Pricing basis', '价格依据')}>{(['midpoint', 'natural', 'custom'] as const).map((b, i) => <button key={b} data-testid={`basis-${b}`} aria-pressed={basis === b} onClick={() => setBasis(b)}>{[t('Midpoint', '中间价'), t('Natural', '对手价'), t('Custom', '自定义')][i]}</button>)}</div>{basis === 'custom' && <label className="fieldrow">{t('Debit / share', '每股净支出')}<input aria-label={t('Debit per share', '每股净支出')} value={custom} inputMode="decimal" onChange={e => setCustom(e.target.value)}/></label>}{invalid}{result && <><small className="help">{t('Total debit · USD', '总净支出 · 美元')}</small><div className="hero" data-testid="debit">{dollars(result.totalDebit)}</div><p>{basis === 'midpoint' ? t('Midpoint is a reference, not a fill.', '中间价是参考值，并非成交价。') : basis === 'natural' ? t('Long ask minus short bid; execution is not guaranteed.', '买入腿卖价减去卖出腿买价，不保证成交。') : t('Your assumed debit; not a recorded fill.', '你输入的假设支出，并非已记录成交。')}</p>{metrics}<small className="help">{t('Gross at expiration. Fees are unknown; net results unavailable.', '到期毛损益。费用未知，净损益不可用。')}</small><button className="primary wide" onClick={() => setView('scenario')}>{t('Explore scenarios', '探索情景')}</button><button className="wide" onClick={() => setView('watch')}>{t('Continue to save & watch', '继续至保存与观察')}</button></>}</section></div>}
    {view === 'scenario' && <div className="layout"><section className="panel controls"><h2>{t('Set the assumptions', '设置假设')}</h2><small className="help">{t('Base: Sep 25, 10:42 ET · $182.40', '基准：9月25日 10:42 美东时间 · $182.40')}</small><div className="group"><div className="row"><span>{t('Underlying price', '标的价格')}</span><strong className="value" data-testid="spot">{dollars(spot, 3)}</strong></div><Choices label={t('Price shock', '价格变化')} values={[-5, -2, 0, 2, 5]} selected={shock} onChange={setShock} format={v => `${plus(v)}%`}/><small className="help">{t('Change from the base. Exact value retained.', '相对于基准的变化，保留精确数值。')}</small></div><div className="group"><div className="row"><span>{t('Elapsed sessions', '经过交易日')}</span><strong>{plus(sessions)} {t(sessions === 1 ? 'session' : 'sessions', '个交易日')}</strong></div><Choices label={t('Elapsed sessions', '经过交易日')} values={[0, 1, 3, 5]} selected={sessions} onChange={setSessions} format={plus}/><small className="help">{t('Next valuation time needs an exchange calendar.', '下一个估值时点需由交易所日历确定。')}</small></div><div className="group"><div className="row"><span>{t('IV shift', 'IV 变化')}</span><strong>{plus(iv)} {t('percentage points', '个百分点')}</strong></div><Choices label={t('IV shift', 'IV 变化')} values={[-5, 0, 5]} selected={iv} onChange={setIv} format={plus}/><small className="help" data-testid="shifted-iv">{t('Parallel shift', '平行移动')}: 35.8 / 34.8% → {shiftedIv('35.8', iv)} / {shiftedIv('34.8', iv)}%</small></div><button className="wide" onClick={() => { setShock(0); setSessions(0); setIv(0); }}>{t('Reset to base', '重置至基准')}</button></section><div className="stack"><section className="notice"><h2>{t('Pre-expiry value unavailable', '到期前估值不可用')}</h2><p>{t('Model and inputs need verification.', '模型与输入仍需验证。')}</p><p>{t('Exercise + dividends · Rates + valuation time · Per-leg IV data', '行权与股息 · 利率与估值时点 · 各合约 IV 数据')}</p><button onClick={() => modal.current?.showModal()}>{t('View model requirements', '查看模型要求')}</button></section><section className="panel"><h2>{t('Expiry reference', '到期参考')}</h2>{invalid}{result && <><p>{t('Selected debit', '已选净支出')} {dollars(result.totalDebit)} · {t('gross, before fees', '费用前毛损益')}</p>{metrics}<Payoff plan={plan} spot={spot} t={t}/><small className="help">{t('Underlying price at expiry (USD)', '到期标的价格（美元）')}</small><p className="chart-caption" data-testid="scenario-pnl">{t('At the selected', '在所选价格')} {dollars(spot, 3)}: <strong>{dollars(expiryPnl(plan, spot).gross)}</strong> {t('at expiration, before fees.', '的到期毛损益，未扣费用。')}</p><small className="help">{t('Expiry payoff only. Time and IV do not change this expiry reference. No pre-expiry curve or probability estimate.', '仅为到期损益。时间与 IV 不改变此到期参考。没有到期前曲线或概率估计。')}</small></>}</section></div></div>}
    {view === 'watch' && <div className="layout"><section className="panel"><h2>{t('A condition worth returning to', '值得再次查看的条件')}</h2><p>{t('On the same completed five-minute bar:', '在同一根已完成的五分钟 K 线上：')}</p><ol className="facts"><li>{t('Close strictly above $182.80', '收盘价严格高于 $182.80')}</li><li>{t('Close strictly above that bar’s session VWAP', '收盘价严格高于该 K 线对应的当日 VWAP')}</li></ol><div className="row"><span>{t('Session', '交易时段')}</span><strong>RTH</strong></div><div className="row"><span>{t('Timezone', '时区')}</span><strong>America/New_York</strong></div><div className="row"><span>{t('Frequency', '频率')}</span><strong>{t('First match per session', '每个交易日首次符合')}</strong></div><small className="help">{t('Only fully post-activation bars qualify. No historical match is delivered retroactively. Missing or stale inputs mean unknown.', '仅启用之后完整形成的 K 线合格。不会补发历史匹配。缺失或过期输入表示未知。')}</small></section><div className="stack"><section className="notice"><h2>{t('Save is not connected in this preview', '此预览尚未连接保存功能')}</h2><p>{t('Your changes are only held in this page. They are not a saved research case.', '你的修改仅保留在当前页面，尚未成为已保存的研究案例。')}</p><button disabled>{t('Save research & watch draft', '保存研究与观察草稿')}</button><small className="help">{t('Account research storage must be connected before you can save this example.', '连接账户研究存储后才能保存此示例。')}</small></section><section className="panel"><span className="pill">{t('Unsaved draft · not armed', '未保存草稿 · 未启用')}</span><h2 style={{ marginTop: 16 }}>{t('Alert activation unavailable', '提醒启用不可用')}</h2><p>{t('This preview cannot monitor completed bars or send notifications.', '此预览无法监测已完成 K 线或发送通知。')}</p><button className="wide" disabled>{t('Activate alert', '启用提醒')}</button><button className="wide" onClick={exportExample} disabled={!result}>{t('Download synthetic example', '下载合成示例')}</button><small className="help">{t('A local example file, not an account save, alert receipt or order.', '本地示例文件，不是账户保存、提醒回执或订单。')}</small><button className="primary wide" onClick={() => setView('review')}>{t('Preview next-session review', '预览下次交易日复盘')}</button></section></div></div>}
    {view === 'review' && <div className="stack"><section className="notice"><h2>{t('A retained research observation', '保留的研究观察')}</h2><p>{t('D2 sample viewed at 10:00 ET. The 09:50–09:55 completed bar matched both conditions; evaluated at 09:55:02.', 'D2 示例于美东时间 10:00 查看。09:50–09:55 的已完成 K 线满足两项条件，于 09:55:02 计算。')}</p><div className="row"><span>{t('Close / session VWAP', '收盘价 / 当日 VWAP')}</span><strong>$184.50 / $183.92</strong></div><span className="pill">{t('Draft, not a delivered alert', '草稿，并非已送达提醒')}</span></section><section className="panel"><h2>{t('Two honest price comparisons', '两种明确的价格比较')}</h2><p>{t('Fixed D1 → D2 synthetic snapshots, one spread. These do not change when you edit the current Plan.', '固定 D1 → D2 合成快照，一组价差。修改当前计划不会改变这些记录。')}</p><div className="comparison"><section><h3>{t('Midpoint reference', '中间价参考')}</h3><p>$200 → $215</p><div className="hero">+$15</div><small className="help">{t('Quote-to-quote change; not a fill or position P&L.', '报价之间的变化，并非成交或持仓损益。')}</small></section><section><h3>{t('Displayed natural entry / exit', '显示的对手价开仓 / 平仓')}</h3><p>$210 → $205</p><div className="hero">−$5</div><small className="help">{t('Before unknown fees; execution was not recorded.', '未扣未知费用；没有记录实际成交。')}</small></section></div></section><div className="layout"><section className="panel"><h2>{t('A source correction', '来源更正')}</h2><p>{t('Episode C: 800 → 600 contracts at $5.25. Premium $420,000 → $315,000.', '事件 C：以 $5.25 计，800 → 600 张。权利金 $420,000 → $315,000。')}</p><p>{t('A–C total: $1,240,000 → $1,135,000. The original as-known record retains $1,240,000.', 'A–C 总额：$1,240,000 → $1,135,000。原始当时已知记录仍保留 $1,240,000。')}</p><strong>{t('This is a correction, not new selling.', '这是更正，不是新增卖出。')}</strong></section><section className="panel"><h2>{t('Newly available open interest', '新披露的未平仓量')}</h2><div className="hero">18,420 → 19,200</div><p>{t('The later OI snapshot does not identify which prints opened positions or who initiated the trade.', '后续持仓快照不能识别哪些成交属于开仓，也不能识别交易发起方。')}</p><small className="help">{t('Research archive and alert disarm remain separate actions. Neither action is connected in this preview.', '归档研究与停用提醒是独立操作。此预览尚未连接这两项操作。')}</small></section></div></div>}
    <footer className="footer"><p>{t('Unsaved synthetic example. No alert or order.', '未保存的合成示例。没有提醒或订单。')}</p><div className="actions">{view !== 'plan' && <button onClick={() => setView('plan')}>{t('Return to Plan', '返回计划')}</button>}{view === 'scenario' && <button className="primary" onClick={() => setView('watch')}>{t('Continue to save & watch', '继续至保存与观察')}</button>}</div></footer>
    </main><dialog ref={modal} aria-labelledby="requirements-title"><h2 id="requirements-title">{t('Before a pre-expiry value is available', '到期前估值所需条件')}</h2><ul className="facts"><li>{t('Named model and version, independently qualified for American equity calls.', '明确的模型与版本，并独立验证其适用于美式股票看涨期权。')}</li><li>{t('Resolved valuation and expiry instants, using the canonical exchange calendar.', '通过统一交易所日历确定估值与到期时点。')}</li><li>{t('Dated dividends, rates, exercise and settlement conventions.', '有日期的股息、利率，以及行权与结算规则。')}</li><li>{t('Synchronized per-leg NBBO and IV, with freshness and entitlement checks.', '同步的各合约 NBBO 与 IV，以及新鲜度和权限核验。')}</li><li>{t('Convergence tests and declared Greek units. No probability or forecast implied.', '收敛测试与明确的希腊值单位。不暗示概率或预测。')}</li></ul><button className="wide" onClick={() => modal.current?.close()}>{t('Close', '关闭')}</button></dialog>
  </>;
}
createRoot(document.getElementById('root')!).render(<App />);
