export const OPTIONS_LEX = {
  knownSubtotal: ["Known subtotal", "已知小计"], gridPositions: ["grid positions", "网格位置"],
  totalIncomplete: ["Complete total unavailable.", "完整合计不可用。"],
  declaredGrid: ["Declared display grid", "源声明的显示网格"], derivedGrid: ["Grid derived from supplied cells", "由已提供单元格形成的网格"],
  sourceCoverageUnknown: ["Source collection coverage unknown", "源采集覆盖范围未知"],
  outsideDisplayedRows: ["In this analytical scope, outside the displayed rows.", "在当前分析范围内，但未包含于所显示行。"],
  revealSelection: ["Reveal selected node", "显示所选节点"],
  options: ["Options", "期权"], overview: ["Overview", "概览"], open: ["Options heatmap", "期权热力图"],
  close: ["Close options panel", "关闭期权面板"], perspectives: ["Options perspective", "期权视角"],
  gamma: ["Gamma", "Gamma"], vanna: ["Vanna", "Vanna"], oi: ["OI", "持仓量"], flow: ["Flow", "资金流"],
  eod: ["EOD SNAPSHOT", "收盘快照"], notIntraday: ["not intraday", "非日内数据"],
  loading: ["Loading options snapshot…", "正在加载期权快照…"], refresh: ["Refresh snapshot", "刷新快照"],
  unavailable: ["No covered snapshot", "暂无覆盖快照"],
  unavailableBody: ["The source did not publish usable data for this symbol and view. No other symbol is substituted.", "数据源尚未为该代码及视角发布可用数据。不会替换为其他代码。"],
  identity: ["Source identity does not match this chart. Values are withheld.", "源数据标识与当前图表不符，已隐藏数值。"],
  session: ["The snapshot has no trustworthy session date. Values are withheld.", "快照缺少可信的交易日期，已隐藏数值。"],
  malformed: ["The source contains an incompatible or duplicate grid. Values are withheld.", "源数据网格格式不兼容或存在重复数据，已隐藏数值。"],
  unsupported: ["This chart symbol does not have a supported US-options root.", "当前图表代码不属于支持的美股期权标的。"],
  failed: ["Refresh failed. The last snapshot remains dated below.", "刷新失败。下方仍显示带日期的上一份快照。"],
  replay: ["EOD options are independent of chart replay; pins are disabled during replay.", "收盘期权快照独立于图表回放；回放期间禁用图表标线。"],
  expiry: ["Expiries", "到期日"], nearest: ["Nearest", "最近"], snapshot0dte: ["Snapshot 0DTE", "快照当日到期"],
  strikes: ["Strike window", "行权价范围"], normalization: ["Color scale", "颜色尺度"],
  scope: ["Scope & display", "范围与显示"], apply: ["Apply view", "应用视图"], cancel: ["Cancel", "取消"],
  pending: ["Pending changes do not alter the map until Apply.", "应用前，待定更改不会改变热力图。"],
  outsideView: ["Selection outside this view. Its identity is retained.", "所选节点不在当前视图内，节点身份仍保留。"],
  nodeContext: ["Node context", "节点上下文"], strikeTotal: ["Strike Σ", "行权价合计"],
  ex0dte: ["Ex-0DTE Σ", "剔除当日到期"], scopeRank: ["Scope rank", "范围排名"],
  strikeShare: ["Share of known |cell net| at strike", "占该行权价已知 |单元格净值|"], expiryMix: ["Expiry mix at this strike", "该行权价到期结构"],
  contextUnavailable: ["Reapply a scope containing this contract to compare it with the current map.", "重新应用包含该合约的范围后，可与当前热力图进行比较。"],
  structureBrief: ["Structure brief", "结构速览"], dominantNode: ["Largest |node|", "最大 |节点|"],
  opposingNode: ["Opposite node", "反向节点"], expiryLead: ["Expiry lead", "到期集中"],
  vsSpot: ["vs spot", "距现价"], cellShare: ["of known |cell values|", "占已知 |单元格值|"], inspectNode: ["Inspect node", "查看节点"],
  scopeCells: ["Scope cells", "范围单元格"],
  marketMemory: ["Market Memory", "市场记忆"], memoryAllExpiry: ["ALL EXPIRIES", "全部到期日"],
  previousAvailable: ["Previous available snapshot", "上一可用快照"], memoryLoading: ["Loading prior snapshot…", "正在加载上一快照…"],
  memoryUnavailable: ["No qualified prior GEX snapshot for this session.", "当前交易日没有合格的历史 GEX 快照。"],
  memoryMismatch: ["Matrix and all-expiry GEX describe different sessions. Comparison withheld.", "矩阵与全部到期 GEX 属于不同交易日，已暂停比较。"],
  memoryArchiveMissing: ["The indexed prior snapshot is unavailable. Live values are not substituted.", "索引中的上一快照不可用，不会用当前数值替代。"],
  netGex: ["All-expiry net GEX", "全部到期净 GEX"], sameStrikeAll: ["Same strike · all expiries", "同行权价 · 全部到期日"],
  memoryDelta: ["Δ vs prior", "较上一快照 Δ"], memorySpot: ["Spot reference", "现价参考"],
  memoryCaution: ["EOD change only. Spot, IV, time and positioning can all contribute; this is not positioning attribution.", "仅表示日终变化。现价、IV、时间与持仓均可能产生影响；这不是持仓变化归因。"],
  global: ["Global scale", "全局尺度"], column: ["Per expiry", "各到期日"],
  columnNote: ["Per-expiry scale: compare intensities within a column, not between columns.", "各列独立归一化：仅可在同列内比较颜色强度。"],
  scaleNote: ["Color saturates at the visible 95th percentile; numbers retain their full magnitude.", "颜色在可见数值的第95百分位达到饱和，数值仍保留实际规模。"],
  positive: ["Positive", "正值"], negative: ["Negative", "负值"], magnitude: ["Intensity = magnitude", "强度代表规模"],
  build: ["Build", "增仓"], unwind: ["Unwind", "减仓"], fewer: ["Fewer", "较少"], more: ["More", "较多"],
  visibleGex: ["Visible net GEX", "可见净 GEX"], visibleOi: ["Visible open interest", "可见持仓量"],
  visibleDoi: ["Visible OI change", "可见持仓变化"], visibleVolume: ["Visible session volume", "可见时段成交量"],
  scopeGex: ["Selected-scope net GEX", "所选范围净 GEX"], scopeOi: ["Selected-scope open interest", "所选范围持仓量"],
  scopeDoi: ["Selected-scope OI change", "所选范围持仓变化"], scopeVolume: ["Selected-scope session volume", "所选范围时段成交量"],
  visibleVanna: ["Visible net VEX", "可见净 VEX"], reference: ["Snapshot reference", "快照参考价"],
  strike: ["Strike", "行权价"], missing: ["Not published", "未发布"], unitsGex: ["$ / +1% spot", "美元 / 现价上涨1%"],
  unitsVanna: ["$ / +1 vol point", "美元 / 波动率上涨1个百分点"], contracts: ["contracts", "份合约"],
  noExpiry: ["No expiry matches this snapshot's session. The front expiry is not 0DTE.", "没有在快照交易日到期的合约。最近到期日不等同于当日到期。"],
  select: ["Select a cell to inspect", "选择单元格查看详情"],
  keyboard: ["Arrow keys navigate · Enter selects · Esc clears", "方向键移动 · 回车选择 · Esc 清除"],
  estimate: ["An OI-based concentration estimate, not a price target or a trade recommendation.", "基于持仓量的集中度估算，并非目标价或交易建议。"],
  model: ["Model assumes dealers long calls / short puts. Exposure sign is not observed buying or selling.", "模型假设做市商做多看涨期权、做空看跌期权。敞口正负并非实际买卖方向。"],
  oiNote: ["Open interest counts open contracts, not bullishness. ΔOI compares source sessions after clearing.", "持仓量是未平仓合约数量，不代表看涨程度。持仓变化基于清算后的源数据时段。"],
  volumeNote: ["Cleared session volume is activity, not a change in open interest or dealer inventory.", "时段成交量反映交易活跃度，不等于持仓量或做市商库存变化。"],
  basis: ["Method & coverage", "方法与覆盖"], partial: ["Some visible cells are missing; the total includes published values only.", "部分可见单元格缺失；合计仅包含已发布数值。"],
  bucket: ["strike buckets", "行权价分组"], visible: ["visible expiries", "可见到期日"],
  pin: ["Pin strike on chart", "在图表标记行权价"], unpin: ["Remove chart pin", "移除图表标线"],
  clear: ["Clear selection", "清除选择"], expand: ["Open Exposure desk", "打开敞口工作台"],
  allExpiries: ["All-expiry strike profile", "全部到期日行权价分布"],
  vannaNote: ["The canonical source publishes Vanna by strike across all expiries. An expiry heatmap is not yet available; legacy matrix VEX uses a different sign convention and is not substituted.", "规范数据源提供涵盖全部到期日的 Vanna 行权价分布。尚无分到期日热力图；旧版网格 VEX 采用不同符号约定，不会用于替代。"],
  tape: ["Activity tape", "交易动态"], volume: ["Session volume", "时段成交量"],
  flowNote: ["A filtered activity feed, not every market trade. Premium and contract count do not identify opening intent, dealer positions, or bullishness.", "这是经过筛选的交易动态，并非全部市场成交。权利金与合约数量不代表开仓意图、做市商持仓或看涨程度。"],
  noFlow: ["No matching activity in the current feed window.", "当前动态窗口没有匹配的交易。"],
  premium: ["premium", "权利金"], call: ["Call", "看涨"], put: ["Put", "看跌"],
  openFlow: ["Open Flow desk", "打开资金流工作台"], untimed: ["Source timing unavailable", "源数据时间不可用"],
  old: ["Older snapshot", "较早快照"],
  publishedOnly: ["published cells only", "仅已发布单元格"],
} as const;
export type OptionsWord = keyof typeof OPTIONS_LEX;
export type OptionsT = (key: OptionsWord) => string;
export const optionsT = (lang: string): OptionsT => (key) => OPTIONS_LEX[key][lang === "zh" ? 1 : 0];
