"use client";
import { useCallback } from "react";
import { useLang, useT } from "./i18n";
/** Feature-local EN/ZH tuples. Language state remains the shared LangProvider.
 * Keeping feature copy out of global LEX avoids loading this workspace on every
 * route and preserves unrelated screen evidence. No mutable registration/store.
 */
export const SECTOR_INTELLIGENCE_LEX: Record<string, [string, string]> = {
  siBrowseGroups: ["Browse company groups", "浏览公司分组"],
  siGroupBrowserClose: ["Close", "关闭"],
  siGroupsIndependent: ["Groups are shown independently of the sector selection.", "公司分组独立于当前板块选择展示。"],
  siFindGroup: ["Find a group", "搜索分组"],
  siGroupsLoading: ["Loading groups…", "正在加载分组…"],
  siGroupsAccess: ["Sign in to read the company groups.", "登录后查看公司分组。"],
  siGroupsUnavailable: ["Company groups are unavailable right now.", "公司分组暂不可用。"],
  siGroupMatch: ["group", "个分组"], siGroupMatches: ["groups", "个分组"],
  siClearGroupSearch: ["Clear search", "清除搜索"],
  siGroupCompany: ["company", "家公司"], siGroupCompanies: ["companies", "家公司"], siGroupSelected: ["Selected", "已选择"],
  siNoGroupMatches: ["No groups match this search.", "没有匹配的分组。"],
  siMoreGroups: ["Show more groups", "显示更多分组"],
  siUseLight: ["Use light view", "使用浅色视图"], siUseDark: ["Use dark view", "使用深色视图"],
  siCompareTitle: ["Compare the companies", "比较公司"],
  siCompareWindow: ["20 trading days · versus the selected group", "20个交易日 · 相对所选分组"],
  siSelectCompany: ["Select company", "选择公司"],
  siSelectedCompany: ["Selected company", "所选公司"],
  siCompanyPrompt: ["Select a company to inspect its performance.", "选择公司以查看其表现。"],
  siCompareAll: ["Show all companies", "显示全部公司"],
  siCompareLess: ["Show fewer", "收起"],
  siFullCompanyTable: ["Open company table", "打开公司列表"],
  siCompareAbsolute: ["Company return", "公司收益"],
  siCompareRelative: ["Versus group", "相对分组"],
  siCompareMethods: ["Comparison details", "比较详情"],
  siCompareMethodsBody: ["Dots use the same percentage-point scale. Company return and relative performance are different measures. Missing values stay blank; selecting or sorting a company does not change its source signal.", "各点使用相同的百分点刻度，公司收益与相对表现是不同指标。缺失值保持为空；选择或排序公司不会改变其来源信号。"],
  siSourceSignalDetails: ["Signal details", "信号详情"],
  siComparisonMissing: ["No comparable values are available.", "暂无可比较数值。"],
  siGroupClock: ["Group snapshot", "分组快照"],
  siOverview: ["Overview", "概览"],
  siGlanceLeading: ["Leading, with mixed timing", "领先，但时机信号不一致"],
  siGlanceLeadingPlain: ["Leading the sector set", "领先于其他板块"],
  siGlanceMixed: ["Read the signals separately", "分别查看各项信号"],
  siGlanceUnavailable: ["Evidence is incomplete", "证据尚不完整"],
  siGlanceLimit: ["Entry timing is not confirmed here.", "此处尚未确认入场时机。"],
  siDataDetails: ["Data details", "数据详情"],
  siShowEvidence: ["Read the evidence", "查看证据"],
  siCompactPartial: ["Some sources are unavailable.", "部分来源暂不可用。"],
  siThemeFreshnessLimited: ["Some theme inputs are stale; freshness varies by source.", "部分主题输入已过期，各来源的新鲜度不同。"],
  siTab: ["Sector Intelligence", "板块情报"],
  siEyebrow: ["UNITED STATES · SECTOR INTELLIGENCE", "美国 · 板块情报"],
  siTitle: ["Sector Intelligence", "板块情报"],
  siSubtitle: ["Leadership, timing and the companies behind it.", "领涨方向、时机与背后的公司。"],
  siIntelligence: ["Intelligence", "情报"], siDossier: ["Dossier", "档案"],
  siCompanies: ["Companies & exposure", "公司与敞口"], siThemes: ["Themes & gaps", "主题与缺口"],
  siSources: ["Source record", "来源记录"], siViews: ["Sector intelligence views", "板块情报视图"],
  siSector: ["Sector", "板块"], siGroup: ["Source group", "来源分组"],
  siChooseGroup: ["Choose a group", "选择分组"], siRefresh: ["Refresh", "刷新"],
  siDated: ["Dated snapshot", "带日期快照"], siUnknownDate: ["Date unavailable", "日期不可用"],
  siSourceOrder: ["Source order", "来源顺序"], siSort: ["Display order", "显示顺序"],
  siByReturn: ["20D return · high to low", "20日收益 · 降序"],
  siByRelative: ["Vs group · high to low", "相对分组 · 降序"], siByTicker: ["Ticker · A–Z", "代码 · A–Z"],
  siSearch: ["Find a ticker", "搜索股票代码"], siAtGlance: ["at a glance", "概览"],
  siRS: ["21D relative-strength rank", "21日相对强度排名"], siRS63: ["63D rank", "63日排名"],
  siParticipation: ["Advancing participation", "上涨参与度"], siAdvancing: ["advancing", "上涨"],
  siDeclining: ["declining", "下跌"], siHeat: ["1M sector heat", "1个月板块热度"],
  siHeatMethod: ["Cap-weighted source field", "来源市值加权字段"],
  siTop5: ["Top-five cap share", "前五大市值占比"], siTiles: ["heatmap names", "热力图成分"],
  siFocus: ["What matters now", "当前重点"], siSeparate: ["Four questions. No blended score.", "四个问题，不混合评分。"],
  siStrength: ["Current strength", "当前强度"], siFormation: ["Formation & change", "形态与变化"],
  siEntry: ["Entry suitability", "入场适用性"], siEvidence: ["Evidence quality", "证据质量"],
  siUnavailable: ["Unavailable", "不可用"], siNotConnected: ["Not connected", "尚未连接"],
  siEntryCopy: ["Strategy and horizon availability is separate from these source labels.", "策略与周期的可入场状态独立于这些来源标签。"],
  siSlow: ["Slow cycle", "慢周期"], siFast: ["Fast rotation", "快速轮动"],
  siAbove200: ["Above 200-day trend", "位于200日趋势上方"], siBelow200: ["Below 200-day trend", "位于200日趋势下方"],
  siTrendUnknown: ["Trend not supplied", "未提供趋势"],
  siPocket: ["Subsector context", "子行业背景"], siEntryOwner: ["Entry-context source", "入场背景来源"],
  siRegimeOwner: ["Regime source", "状态来源"], siWhyDiffer: ["Why these can differ", "为何可以不同"],
  siSplitCopy: ["Entry context, price regime and theme readiness answer different questions. None grants a strategy entry here.", "入场背景、价格状态与主题就绪度回答不同问题，均不在此授予策略入场资格。"],
  siPriced: ["priced", "已定价"], siMembers: ["source members", "来源成分"],
  siDispersion: ["Leadership dispersion", "领涨分化"], siDispersionCopy: ["20-session performance within the selected source group.", "所选来源分组内20个交易日的表现。"],
  siSeeCompanies: ["Explore companies", "查看公司"], siTaxonomy: ["Coverage matters", "覆盖范围很重要"],
  siTaxonomyCopy: ["A hardware group is not a CPU-only group. A verified CPU exposure mapping is not connected here.", "硬件分组不等于纯CPU分组，此处尚未连接经验证的CPU敞口映射。"],
  siBusiness: ["Business drivers", "业务驱动因素"],
  siBusinessCopy: ["Orders, pricing, inventory, capacity, estimate revisions and valuation evidence are not connected. Price strength is not a substitute.", "尚未连接订单、定价、库存、产能、盈利预期修正与估值证据，价格强势不能替代这些证据。"],
  siResearchOnly: ["Research context", "研究背景"],
  siResearchCopy: ["Source signals are shown separately. This view does not create a buy signal or position size.", "来源信号分开展示，此视图不会生成买入信号或仓位大小。"],
  siConcentration: ["Sector concentration", "板块集中度"],
  siCohortCopy: ["Heatmap membership and advancing participation are separate cohorts. Matching counts do not prove identical holdings.", "热力图成分与上涨参与度来自不同样本，数量相同不代表持仓相同。"],
  siConcentrationMissing: ["An exact, priced heatmap cohort is required before showing this share.", "需要精确且已定价的热力图样本，才能显示此占比。"],
  siClockCopy: ["Different horizons remain visible; neither clock cancels the other.", "不同周期同时显示，任一时钟都不会抹去另一时钟。"],
  siSourceCount: ["sources received", "个来源已接收"], siPartial: ["Some evidence is unavailable", "部分证据不可用"],
  siPartialCopy: ["Available source data remains visible. Open the source record for dates and connection status.", "已获取的来源数据仍会显示，可在来源记录查看日期与连接状态。"],
  siOpenSources: ["Review sources", "查看来源"], siRetry: ["Try again", "重试"],
  siLoading: ["Loading sector evidence…", "正在加载板块证据…"],
  siAccess: ["Sector data requires access", "板块数据需要访问权限"],
  siAccessCopy: ["The data owner did not authorize this request. Sign in or check your account access; no sample values are substituted.", "数据来源未授权此请求，请登录或检查账户权限。系统不会以示例数值替代。"],
  siSignIn: ["Sign in", "登录"], siMissingTitle: ["Sector evidence is not available", "板块证据暂不可用"],
  siMissingCopy: ["The selected sector has no readable owner snapshot. Other views can still show their available sources.", "所选板块没有可读取的来源快照，其他视图仍可展示已获取的来源。"],
  siInvalidCopy: ["The source response did not match the supported owner fields. No values were inferred.", "来源响应与支持的字段不匹配，系统没有推断任何数值。"],
  siTicker: ["Ticker", "代码"], siPrice: ["Source price", "来源价格"],
  siReturn20: ["20D return", "20日收益"], siRelative: ["Vs group", "相对分组"],
  siTier: ["Source tier", "来源等级"], siTicks: ["Confirmations", "确认次数"],
  siSourceFlag: ["Source availability", "来源可用状态"], siState: ["Source state", "来源状态"],
  siYes: ["Yes", "是"], siNo: ["No", "否"], siSourceUnrated: ["Not rated", "未评级"],
  siCompanyCaution: ["The source stock_buyable flag is not the canonical strategy-by-horizon availability contract. Sorting changes display order only.", "来源stock_buyable标记不是按策略与周期划分的正式可入场合约；排序只改变显示顺序。"],
  siOpenCompany: ["Open company research", "打开公司研究"],
  siNoMembers: ["No verified company rows are available for this source group.", "此来源分组暂无经验证的公司行。"],
  siNoMatches: ["No tickers match this search.", "没有匹配的股票代码。"],
  siShowing: ["shown", "已显示"], siThemeContext: ["Theme context", "主题背景"],
  siThemeScope: ["The theme source universe is shown separately, not as verified sector membership.", "主题来源全集单独展示，不代表已验证的板块成员关系。"],
  siThemeStage: ["Theme stage", "主题阶段"], siThemeReady: ["Source entry-ready", "来源入场就绪"],
  siNoThemes: ["No readable theme rows are available.", "暂无可读取的主题行。"],
  siSourceRecord: ["Source record", "来源记录"], siSourceRecordCopy: ["One clock per source. Fetch time never replaces market time.", "每个来源保留自身时间，抓取时间不会替代市场数据时间。"],
  siSnapshotDate: ["Market as-of", "市场数据截至"], siFetched: ["Fetched at", "抓取时间"],
  siReceipt: ["Technical receipt", "技术凭据"], siSourcePath: ["Owner path", "来源路径"],
  siHash: ["Snapshot SHA-256", "快照SHA-256"], siFeedSector: ["Sector Central", "板块中心"],
  siFeedConfluence: ["Subsector confluence", "子行业共振"], siFeedThemes: ["Theme state", "主题状态"],
  siFeedHeatmap: ["Market heatmap", "市场热力图"], siStatusReady: ["Received", "已接收"],
  siStatusLoading: ["Loading", "加载中"], siStatusAccess: ["Access required", "需要权限"],
  siStatusUnavailable: ["Unavailable", "不可用"], siStatusInvalid: ["Unrecognized data", "数据不匹配"],
  siStatusError: ["Connection failed", "连接失败"], siStale: ["Source marked stale", "来源标记为过期"],
  siReplay: ["History & corrections", "历史与修正"],
  siReplayCopy: ["A dated snapshot is not point-in-time replay. Historical membership and correction lineage are not connected to this view yet.", "带日期快照并非时点回放，此视图尚未连接历史成员关系与修正链。"],
  siCohort: ["Cohort binding", "样本绑定"], siMembershipCopy: ["Company rows belong to the selected source group, not automatically to the sector ETF holdings.", "公司行属于所选来源分组，并不自动代表板块ETF持仓。"],
  siStateLeading: ["Leading", "领先"], siStateLagging: ["Lagging", "落后"],
  siStateCautious: ["Cautious", "谨慎"], siStateMixed: ["Mixed", "混合"],
  siStateExtended: ["Extended", "偏离较大"], siStateTurn: ["Turn signaled", "转折信号"],
  siStateWatch: ["Watch", "观察"], siStateEarly: ["Early", "早期"],
  siStateConfirmed: ["Confirmed", "已确认"], siStateMature: ["Mature", "成熟"],
  siStateDeteriorating: ["Deteriorating", "走弱"], siStateLong: ["Long bias", "偏多"],
  siStateNeutral: ["Neutral", "中性"], siStateRolling: ["Rolling over", "转弱"],
  siStateImproving: ["Improving", "改善"], siStateConstructive: ["Constructive", "偏积极"],
  siSelectSources: ["Read source details", "阅读来源详情"],
};

export function useSectorT() {
  const { lang } = useLang();
  const sharedT = useT();
  return useCallback((key: string, fallback?: string): string => {
    const pair = SECTOR_INTELLIGENCE_LEX[key];
    return pair ? pair[lang === "zh" ? 1 : 0] : sharedT(key, fallback);
  }, [lang, sharedT]);
}
