import type { Lang } from "@/lib/i18n";

// Pure feature copy follows the existing visualIntelligenceCopy pick convention.
const pick = (lang: Lang, en: string, zh: string): string => lang === "zh" ? zh : en;
export const AUCTION_COPY: Record<string, (lang: Lang) => string> = {
  saTitle: (lang: Lang) => pick(lang, "Sovereign auctions — observed context", "主权债拍卖 — 已观测背景"),
  saNotScored: (lang: Lang) => pick(lang, "Not scored", "未评分"),
  saLoading: (lang: Lang) => pick(lang, "Loading context", "正在加载背景"),
  saUnavailable: (lang: Lang) => pick(lang, "Auction context unavailable", "拍卖背景不可用"),
  saSignIn: (lang: Lang) => pick(lang, "Sign in required", "需要登录"),
  saNotEntitled: (lang: Lang) => pick(lang, "Subscription access required", "需要订阅权限"),
  saObservedEpisodes: (lang: Lang) => pick(lang, "observed episodes", "个已观测拍卖事件"),
  saResearchOnly: (lang: Lang) => pick(lang, "Research only · context only", "仅供研究 · 仅供背景参考"),
  saFreshnessUnassessed: (lang: Lang) => pick(lang, "Freshness unassessed", "时效性未评估"),
  saCutoff: (lang: Lang) => pick(lang, "Decision cutoff (UTC)", "决策截止时间（UTC）"),
  saObservedAt: (lang: Lang) => pick(lang, "Source observed at", "来源观测时间"),
  saUnknown: (lang: Lang) => pick(lang, "Unknown", "未知"),
  saClassBill: (lang: Lang) => pick(lang, "Treasury bill", "短期国债"),
  saClassCmb: (lang: Lang) => pick(lang, "Cash management bill", "现金管理国库券"),
  saClassNote: (lang: Lang) => pick(lang, "Treasury note", "中期国债"),
  saClassBond: (lang: Lang) => pick(lang, "Treasury bond", "长期国债"),
  saClassTips: (lang: Lang) => pick(lang, "Inflation-protected Treasury (TIPS)", "通胀保值国债（TIPS）"),
  saClassFrn: (lang: Lang) => pick(lang, "Floating-rate Treasury (FRN)", "浮动利率国债（FRN）"),
  saTermYear: (lang: Lang) => pick(lang, "{n}-year", "{n}年"),
  saTermMonth: (lang: Lang) => pick(lang, "{n}-month", "{n}个月"),
  saTermWeek: (lang: Lang) => pick(lang, "{n}-week", "{n}周"),
  saTermDay: (lang: Lang) => pick(lang, "{n}-day", "{n}天"),
  saAnnounced: (lang: Lang) => pick(lang, "Auction announced", "拍卖已公告"),
  saTentative: (lang: Lang) => pick(lang, "Tentative schedule", "暂定日程"),
  saAwaitingResult: (lang: Lang) => pick(lang, "Awaiting observed results", "等待观测结果"),
  saIssueDatePassed: (lang: Lang) => pick(lang, "Issue date has passed · settlement not observed", "发行日期已过 · 尚未观测到结算"),
  saIssueDateNotPassed: (lang: Lang) => pick(lang, "Issue date has not passed · settlement not observed", "发行日期尚未过 · 尚未观测到结算"),
  saSourceDetails: (lang: Lang) => pick(lang, "Source details", "来源详情"),
  saEpisodeId: (lang: Lang) => pick(lang, "Event identifier", "事件标识"),
  saSourceLabel: (lang: Lang) => pick(lang, "Source label and class", "来源名称与类别"),
  saSourceAmount: (lang: Lang) => pick(lang, "Exact source amount (USD)", "来源精确金额（美元）"),
  saDegraded: (lang: Lang) => pick(lang, "Source coverage degraded", "来源覆盖降级"),
  saEmpty: (lang: Lang) => pick(lang, "No episodes in the observed set; coverage is not a complete universe", "已观测集合中没有拍卖事件；覆盖不代表完整范围"),
  saAuctionDate: (lang: Lang) => pick(lang, "Auction date", "拍卖日期"),
  saIssueDate: (lang: Lang) => pick(lang, "Issue date", "发行日期"),
  saDeadline: (lang: Lang) => pick(lang, "Competitive deadline (UTC)", "竞争性投标截止时间（UTC）"),
  saKnownAt: (lang: Lang) => pick(lang, "Known at", "获知时间"),
  saSourceState: (lang: Lang) => pick(lang, "Source state", "来源状态"),
  saPhysicalState: (lang: Lang) => pick(lang, "Auction state", "拍卖状态"),
  saIssueState: (lang: Lang) => pick(lang, "Issue calendar state", "发行日历状态"),
  saOffering: (lang: Lang) => pick(lang, "Offering amount", "发行金额"),
  saResultsNotObserved: (lang: Lang) => pick(lang, "Results not observed", "尚未观测到结果"),
  saResultsObserved: (lang: Lang) => pick(lang, "Results observed", "已观测到结果"),
  saNullReasons: (lang: Lang) => pick(lang, "Null reasons", "空值原因"),
  saOfficialSource: (lang: Lang) => pick(lang, "Official source", "官方来源"),
  saShowing: (lang: Lang) => pick(lang, "Showing", "显示"),
  saBoundedList: (lang: Lang) => pick(lang, "Display list is bounded", "显示列表有数量上限"),
  saShowMore: (lang: Lang) => pick(lang, "Show up to 24 episodes", "显示最多 24 个拍卖事件"),
  saSources: (lang: Lang) => pick(lang, "Source observations", "来源观测"),
  saLatestAttempt: (lang: Lang) => pick(lang, "Latest attempt", "最近尝试"),
  saLastValid: (lang: Lang) => pick(lang, "Last valid observation", "最近有效观测"),
  saAgeAtCutoff: (lang: Lang) => pick(lang, "Observation age at cutoff", "截止时的观测年龄"),
  saSeconds: (lang: Lang) => pick(lang, "seconds", "秒"),
  saBodyReceipt: (lang: Lang) => pick(lang, "Last successful body receipt", "最近成功响应接收时间"),
  saLatestFailure: (lang: Lang) => pick(lang, "Latest failure", "最近失败"),
};

export function auctionText(key: string, lang: Lang, fallback?: string): string {
  const entry = AUCTION_COPY[key];
  return entry ? entry(lang) : (fallback ?? key);
}
