SET ROLE authenticated;
SET request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';
DO $bootstrap$
DECLARE
  owner_a constant uuid := '11111111-1111-4111-8111-111111111111';
  owner_b constant uuid := '12222222-2222-4222-8222-222222222222';
  op_a constant uuid := '41111111-1111-4111-8111-111111111111';
  op_b constant uuid := '42222222-2222-4222-8222-222222222222';
  item constant jsonb := '{"id":"legacy-a","kind":"hline","points":[{"p":9,"t":"2024-01-01"}],"color":"#abc","meta":{"note":"preserved"}}';
  canonical jsonb;
  before_rows jsonb;
  after_rows jsonb;
  first_snapshot jsonb;
  result jsonb;
  token text;
  pass_count integer := 0;
  rejected boolean;
BEGIN
  DELETE FROM public.drawings WHERE symbol='BOOTSTRAP';
  first_snapshot := public.read_drawings_collection('BOOTSTRAP');
  IF first_snapshot->>'revision' IS NOT NULL OR first_snapshot->'drawings'<>'[]'::jsonb THEN RAISE EXCEPTION 'FAIL empty GET'; END IF;
  pass_count:=pass_count+1;
  INSERT INTO public.drawings(id,user_id,symbol,kind,data) VALUES(
    '51111111-1111-4111-8111-111111111111',owner_a,'BOOTSTRAP','__collection_v1',
    jsonb_build_object('schemaVersion',1,'revision','61111111-1111-4111-8111-111111111111','drawings',jsonb_build_array(item)));
  SELECT jsonb_agg(to_jsonb(d) ORDER BY id) INTO before_rows FROM public.drawings d WHERE symbol='BOOTSTRAP';
  first_snapshot:=public.read_drawings_collection('BOOTSTRAP');
  SELECT jsonb_agg(to_jsonb(d) ORDER BY id) INTO after_rows FROM public.drawings d WHERE symbol='BOOTSTRAP';
  token:=first_snapshot->>'revision';canonical:=first_snapshot->'drawings';
  IF before_rows IS DISTINCT FROM after_rows OR token !~ '^legacy:[0-9a-f]{64}$'
    OR canonical->0->'points'<>item->'points' OR canonical->0->'meta'<>item->'meta' THEN RAISE EXCEPTION 'FAIL read-only legacy collection'; END IF;
  pass_count:=pass_count+1;
  PERFORM set_config('TimeZone','Asia/Hong_Kong',true);
  IF public.read_drawings_collection('BOOTSTRAP')->>'revision'<>token THEN RAISE EXCEPTION 'FAIL timezone-independent token'; END IF;
  PERFORM set_config('TimeZone','UTC',true);pass_count:=pass_count+1;
  result:=public.replace_drawings_collection('BOOTSTRAP',canonical,NULL,op_a);
  IF result->>'code'<>'revision_conflict' THEN RAISE EXCEPTION 'FAIL blind legacy replace refused'; END IF;
  pass_count:=pass_count+1;
  result:=public.replace_drawings_collection('BOOTSTRAP',canonical,token,op_a);
  IF result->>'ok'<>'true' THEN RAISE EXCEPTION 'FAIL initial legacy CAS'; END IF;
  IF (SELECT data->'prior_operations' FROM public.drawings WHERE symbol='BOOTSTRAP')<>'[]'::jsonb THEN RAISE EXCEPTION 'FAIL no fabricated legacy receipts'; END IF;
  pass_count:=pass_count+1;
  SELECT jsonb_agg(to_jsonb(d) ORDER BY id) INTO before_rows FROM public.drawings d WHERE symbol='BOOTSTRAP';
  result:=public.replace_drawings_collection('BOOTSTRAP',canonical,token,op_a);
  SELECT jsonb_agg(to_jsonb(d) ORDER BY id) INTO after_rows FROM public.drawings d WHERE symbol='BOOTSTRAP';
  IF result->>'idempotentReplay'<>'true' OR before_rows IS DISTINCT FROM after_rows THEN RAISE EXCEPTION 'FAIL lost first reply replay'; END IF;
  pass_count:=pass_count+1;
  result:=public.replace_drawings_collection('BOOTSTRAP','[]'::jsonb,token,op_b);
  IF result->>'code'<>'revision_conflict' THEN RAISE EXCEPTION 'FAIL divergent legacy-token second writer'; END IF;
  pass_count:=pass_count+1;
  DELETE FROM public.drawings WHERE symbol='BOOTSTRAP';
  INSERT INTO public.drawings(id,user_id,symbol,kind,data) VALUES('51111111-1111-4111-8111-111111111111',owner_a,'BOOTSTRAP','hline',item-'id');
  first_snapshot:=public.read_drawings_collection('BOOTSTRAP');token:=first_snapshot->>'revision';
  IF first_snapshot->0 IS NOT NULL OR first_snapshot->'drawings'->0->>'id'<>'51111111-1111-4111-8111-111111111111'
    OR first_snapshot->'drawings'->0->'points'<>item->'points' THEN RAISE EXCEPTION 'FAIL legacy individual geometry/id'; END IF;
  pass_count:=pass_count+1;
  UPDATE public.drawings SET data=jsonb_set(data,'{color}','"#def"') WHERE symbol='BOOTSTRAP';
  SELECT jsonb_agg(to_jsonb(d) ORDER BY id) INTO before_rows FROM public.drawings d WHERE symbol='BOOTSTRAP';
  result:=public.replace_drawings_collection('BOOTSTRAP',first_snapshot->'drawings',token,op_a);
  SELECT jsonb_agg(to_jsonb(d) ORDER BY id) INTO after_rows FROM public.drawings d WHERE symbol='BOOTSTRAP';
  IF result->>'code'<>'revision_conflict' OR before_rows IS DISTINCT FROM after_rows THEN RAISE EXCEPTION 'FAIL in-place legacy edit preserved'; END IF;
  pass_count:=pass_count+1;
  first_snapshot:=public.read_drawings_collection('BOOTSTRAP');token:=first_snapshot->>'revision';
  INSERT INTO public.drawings(id,user_id,symbol,kind,data) VALUES('52222222-2222-4222-8222-222222222222',owner_a,'BOOTSTRAP','hline',jsonb_set(item,'{id}','"legacy-b"'));
  result:=public.replace_drawings_collection('BOOTSTRAP',first_snapshot->'drawings',token,op_a);
  IF result->>'code'<>'revision_conflict' OR (SELECT count(*) FROM public.drawings WHERE symbol='BOOTSTRAP')<>2 THEN RAISE EXCEPTION 'FAIL concurrent legacy insert'; END IF;
  pass_count:=pass_count+1;
  first_snapshot:=public.read_drawings_collection('BOOTSTRAP');token:=first_snapshot->>'revision';
  DELETE FROM public.drawings WHERE id='52222222-2222-4222-8222-222222222222';
  result:=public.replace_drawings_collection('BOOTSTRAP',first_snapshot->'drawings',token,op_a);
  IF result->>'code'<>'revision_conflict' OR (SELECT count(*) FROM public.drawings WHERE symbol='BOOTSTRAP')<>1 THEN RAISE EXCEPTION 'FAIL concurrent legacy delete'; END IF;
  pass_count:=pass_count+1;
  -- Ambiguous stored shapes and unsupported geometry must remain recoverable.
  UPDATE public.drawings SET data=jsonb_set(data,'{points}','[]'::jsonb) WHERE symbol='BOOTSTRAP';
  SELECT jsonb_agg(to_jsonb(d) ORDER BY id) INTO before_rows FROM public.drawings d WHERE symbol='BOOTSTRAP';
  rejected:=false;
  BEGIN PERFORM public.read_drawings_collection('BOOTSTRAP'); EXCEPTION WHEN SQLSTATE '22000' THEN rejected:=true; END;
  SELECT jsonb_agg(to_jsonb(d) ORDER BY id) INTO after_rows FROM public.drawings d WHERE symbol='BOOTSTRAP';
  IF NOT rejected OR before_rows IS DISTINCT FROM after_rows THEN RAISE EXCEPTION 'FAIL malformed geometry retained'; END IF;
  pass_count:=pass_count+1;
  DELETE FROM public.drawings WHERE symbol='BOOTSTRAP';
  INSERT INTO public.drawings(id,user_id,symbol,kind,data) VALUES('51111111-1111-4111-8111-111111111111',owner_a,'BOOTSTRAP','__collection_v1',jsonb_build_object('schemaVersion',1,'drawings',canonical,'operation_id',op_a));
  rejected:=false;
  BEGIN PERFORM public.read_drawings_collection('BOOTSTRAP'); EXCEPTION WHEN SQLSTATE '22000' THEN rejected:=true; END;
  IF NOT rejected OR (SELECT count(*) FROM public.drawings WHERE symbol='BOOTSTRAP')<>1 THEN RAISE EXCEPTION 'FAIL partial operation metadata retained'; END IF;
  pass_count:=pass_count+1;
  UPDATE public.drawings SET data=jsonb_build_object('schemaVersion',1,'drawings',canonical) WHERE symbol='BOOTSTRAP';
  INSERT INTO public.drawings(id,user_id,symbol,kind,data) VALUES('52222222-2222-4222-8222-222222222222',owner_a,'BOOTSTRAP','__collection_v1',jsonb_build_object('schemaVersion',1,'drawings',canonical));
  rejected:=false;
  BEGIN PERFORM public.read_drawings_collection('BOOTSTRAP'); EXCEPTION WHEN SQLSTATE '22000' THEN rejected:=true; END;
  IF NOT rejected OR (SELECT count(*) FROM public.drawings WHERE symbol='BOOTSTRAP')<>2 THEN RAISE EXCEPTION 'FAIL duplicate collection retained'; END IF;
  pass_count:=pass_count+1;
  UPDATE public.drawings SET kind='hline',data=item WHERE id='52222222-2222-4222-8222-222222222222';
  rejected:=false;
  BEGIN PERFORM public.read_drawings_collection('BOOTSTRAP'); EXCEPTION WHEN SQLSTATE '22000' THEN rejected:=true; END;
  IF NOT rejected OR (SELECT count(*) FROM public.drawings WHERE symbol='BOOTSTRAP')<>2 THEN RAISE EXCEPTION 'FAIL mixed legacy shape retained'; END IF;
  pass_count:=pass_count+1;
  RAISE NOTICE 'BOOTSTRAP_CASES=%',pass_count;
END;
$bootstrap$;
RESET ROLE;
