DO $test$
DECLARE v jsonb := $valid$[{"id":"user-1","kind":"trendline","schemaVersion":1,"source":"user","points":[{"t":"2026-10-01","p":10},{"t":"2026-10-02","p":12}]}]$valid$::jsonb; candidate jsonb; rejected boolean; count_pass integer:=0; op uuid:='22222222-2222-4222-8222-222222222222';
BEGIN
 candidate:=v;
 rejected:=false;
 BEGIN PERFORM public.validate_drawing_replace_input('AAPL',candidate,op); EXCEPTION WHEN SQLSTATE '22023' THEN rejected:=true; END;
 IF rejected IS DISTINCT FROM false THEN RAISE EXCEPTION 'FAIL: valid normalized user'; END IF;
 count_pass:=count_pass+1; RAISE NOTICE 'PASS: valid normalized user';
 candidate:='[]'::jsonb;
 rejected:=false;
 BEGIN PERFORM public.validate_drawing_replace_input('AAPL',candidate,op); EXCEPTION WHEN SQLSTATE '22023' THEN rejected:=true; END;
 IF rejected IS DISTINCT FROM false THEN RAISE EXCEPTION 'FAIL: clear tombstone'; END IF;
 count_pass:=count_pass+1; RAISE NOTICE 'PASS: clear tombstone';
 candidate:=v||v;
 rejected:=false;
 BEGIN PERFORM public.validate_drawing_replace_input('AAPL',candidate,op); EXCEPTION WHEN SQLSTATE '22023' THEN rejected:=true; END;
 IF rejected IS DISTINCT FROM true THEN RAISE EXCEPTION 'FAIL: duplicate IDs'; END IF;
 count_pass:=count_pass+1; RAISE NOTICE 'PASS: duplicate IDs';
 candidate:=v||jsonb_set(v,'{0,id}','" user-1 "');
 rejected:=false;
 BEGIN PERFORM public.validate_drawing_replace_input('AAPL',candidate,op); EXCEPTION WHEN SQLSTATE '22023' THEN rejected:=true; END;
 IF rejected IS DISTINCT FROM true THEN RAISE EXCEPTION 'FAIL: trimmed duplicate IDs'; END IF;
 count_pass:=count_pass+1; RAISE NOTICE 'PASS: trimmed duplicate IDs';
 candidate:=v#-'{0,id}';
 rejected:=false;
 BEGIN PERFORM public.validate_drawing_replace_input('AAPL',candidate,op); EXCEPTION WHEN SQLSTATE '22023' THEN rejected:=true; END;
 IF rejected IS DISTINCT FROM true THEN RAISE EXCEPTION 'FAIL: missing ID'; END IF;
 count_pass:=count_pass+1; RAISE NOTICE 'PASS: missing ID';
 candidate:=jsonb_set(v,'{0,id}','" "');
 rejected:=false;
 BEGIN PERFORM public.validate_drawing_replace_input('AAPL',candidate,op); EXCEPTION WHEN SQLSTATE '22023' THEN rejected:=true; END;
 IF rejected IS DISTINCT FROM true THEN RAISE EXCEPTION 'FAIL: empty ID'; END IF;
 count_pass:=count_pass+1; RAISE NOTICE 'PASS: empty ID';
 candidate:=jsonb_set(v,'{0,kind}','"not_a_tool"');
 rejected:=false;
 BEGIN PERFORM public.validate_drawing_replace_input('AAPL',candidate,op); EXCEPTION WHEN SQLSTATE '22023' THEN rejected:=true; END;
 IF rejected IS DISTINCT FROM true THEN RAISE EXCEPTION 'FAIL: unknown kind'; END IF;
 count_pass:=count_pass+1; RAISE NOTICE 'PASS: unknown kind';
 candidate:=jsonb_set(v,'{0,points}','[]');
 rejected:=false;
 BEGIN PERFORM public.validate_drawing_replace_input('AAPL',candidate,op); EXCEPTION WHEN SQLSTATE '22023' THEN rejected:=true; END;
 IF rejected IS DISTINCT FROM true THEN RAISE EXCEPTION 'FAIL: too few points'; END IF;
 count_pass:=count_pass+1; RAISE NOTICE 'PASS: too few points';
 candidate:=jsonb_set(v,'{0,points}',(v->0->'points')||((v->0->'points')->0));
 rejected:=false;
 BEGIN PERFORM public.validate_drawing_replace_input('AAPL',candidate,op); EXCEPTION WHEN SQLSTATE '22023' THEN rejected:=true; END;
 IF rejected IS DISTINCT FROM true THEN RAISE EXCEPTION 'FAIL: too many points'; END IF;
 count_pass:=count_pass+1; RAISE NOTICE 'PASS: too many points';
 candidate:=jsonb_set(v,'{0,source}','"ai"');
 rejected:=false;
 BEGIN PERFORM public.validate_drawing_replace_input('AAPL',candidate,op); EXCEPTION WHEN SQLSTATE '22023' THEN rejected:=true; END;
 IF rejected IS DISTINCT FROM true THEN RAISE EXCEPTION 'FAIL: AI source'; END IF;
 count_pass:=count_pass+1; RAISE NOTICE 'PASS: AI source';
 candidate:=jsonb_set(v,'{0,source}','"detector"');
 rejected:=false;
 BEGIN PERFORM public.validate_drawing_replace_input('AAPL',candidate,op); EXCEPTION WHEN SQLSTATE '22023' THEN rejected:=true; END;
 IF rejected IS DISTINCT FROM true THEN RAISE EXCEPTION 'FAIL: detector source'; END IF;
 count_pass:=count_pass+1; RAISE NOTICE 'PASS: detector source';
 candidate:=jsonb_set(jsonb_set(v,'{0,id}','"ai_legacy"'),'{0,by}','"ai"');
 rejected:=false;
 BEGIN PERFORM public.validate_drawing_replace_input('AAPL',candidate,op); EXCEPTION WHEN SQLSTATE '22023' THEN rejected:=true; END;
 IF rejected IS DISTINCT FROM false THEN RAISE EXCEPTION 'FAIL: explicit user overrides legacy AI hints'; END IF;
 count_pass:=count_pass+1; RAISE NOTICE 'PASS: explicit user overrides legacy AI hints';
 candidate:=v#-'{0,schemaVersion}';
 rejected:=false;
 BEGIN PERFORM public.validate_drawing_replace_input('AAPL',candidate,op); EXCEPTION WHEN SQLSTATE '22023' THEN rejected:=true; END;
 IF rejected IS DISTINCT FROM true THEN RAISE EXCEPTION 'FAIL: missing schema'; END IF;
 count_pass:=count_pass+1; RAISE NOTICE 'PASS: missing schema';
 candidate:=jsonb_set(v,'{0,points,0,p}','"10"');
 rejected:=false;
 BEGIN PERFORM public.validate_drawing_replace_input('AAPL',candidate,op); EXCEPTION WHEN SQLSTATE '22023' THEN rejected:=true; END;
 IF rejected IS DISTINCT FROM true THEN RAISE EXCEPTION 'FAIL: price string'; END IF;
 count_pass:=count_pass+1; RAISE NOTICE 'PASS: price string';
 candidate:=jsonb_set(v,'{0,points,0,p}','1e400');
 rejected:=false;
 BEGIN PERFORM public.validate_drawing_replace_input('AAPL',candidate,op); EXCEPTION WHEN SQLSTATE '22023' THEN rejected:=true; END;
 IF rejected IS DISTINCT FROM true THEN RAISE EXCEPTION 'FAIL: price overflow 1e400'; END IF;
 count_pass:=count_pass+1; RAISE NOTICE 'PASS: price overflow 1e400';
 candidate:=jsonb_set(v,'{0,points,0,p}','1e308');
 rejected:=false;
 BEGIN PERFORM public.validate_drawing_replace_input('AAPL',candidate,op); EXCEPTION WHEN SQLSTATE '22023' THEN rejected:=true; END;
 IF rejected IS DISTINCT FROM false THEN RAISE EXCEPTION 'FAIL: large finite price'; END IF;
 count_pass:=count_pass+1; RAISE NOTICE 'PASS: large finite price';
 candidate:=jsonb_set(v,'{0,points,0,t}','" "');
 rejected:=false;
 BEGIN PERFORM public.validate_drawing_replace_input('AAPL',candidate,op); EXCEPTION WHEN SQLSTATE '22023' THEN rejected:=true; END;
 IF rejected IS DISTINCT FROM true THEN RAISE EXCEPTION 'FAIL: empty point time'; END IF;
 count_pass:=count_pass+1; RAISE NOTICE 'PASS: empty point time';
 candidate:=jsonb_set(v,'{0,points,0,t}','null');
 rejected:=false;
 BEGIN PERFORM public.validate_drawing_replace_input('AAPL',candidate,op); EXCEPTION WHEN SQLSTATE '22023' THEN rejected:=true; END;
 IF rejected IS DISTINCT FROM true THEN RAISE EXCEPTION 'FAIL: null point time'; END IF;
 count_pass:=count_pass+1; RAISE NOTICE 'PASS: null point time';
 candidate:=jsonb_set(v,'{0,points,0,t}','{}');
 rejected:=false;
 BEGIN PERFORM public.validate_drawing_replace_input('AAPL',candidate,op); EXCEPTION WHEN SQLSTATE '22023' THEN rejected:=true; END;
 IF rejected IS DISTINCT FROM true THEN RAISE EXCEPTION 'FAIL: object point time'; END IF;
 count_pass:=count_pass+1; RAISE NOTICE 'PASS: object point time';
 candidate:='{}'::jsonb;
 rejected:=false;
 BEGIN PERFORM public.validate_drawing_replace_input('AAPL',candidate,op); EXCEPTION WHEN SQLSTATE '22023' THEN rejected:=true; END;
 IF rejected IS DISTINCT FROM true THEN RAISE EXCEPTION 'FAIL: non-array'; END IF;
 count_pass:=count_pass+1; RAISE NOTICE 'PASS: non-array';
 candidate:=NULL::jsonb;
 rejected:=false;
 BEGIN PERFORM public.validate_drawing_replace_input('AAPL',candidate,op); EXCEPTION WHEN SQLSTATE '22023' THEN rejected:=true; END;
 IF rejected IS DISTINCT FROM true THEN RAISE EXCEPTION 'FAIL: SQL null'; END IF;
 count_pass:=count_pass+1; RAISE NOTICE 'PASS: SQL null';
 candidate:=(SELECT jsonb_agg(jsonb_set(v->0,'{id}',to_jsonb('id-'||i))) FROM generate_series(1,501) i);
 rejected:=false;
 BEGIN PERFORM public.validate_drawing_replace_input('AAPL',candidate,op); EXCEPTION WHEN SQLSTATE '22023' THEN rejected:=true; END;
 IF rejected IS DISTINCT FROM true THEN RAISE EXCEPTION 'FAIL: 501 drawings'; END IF;
 count_pass:=count_pass+1; RAISE NOTICE 'PASS: 501 drawings';
 candidate:=jsonb_set(v,'{0,meta}',jsonb_build_object('text',repeat('😀',500001)));
 rejected:=false;
 BEGIN PERFORM public.validate_drawing_replace_input('AAPL',candidate,op); EXCEPTION WHEN SQLSTATE '22023' THEN rejected:=true; END;
 IF rejected IS DISTINCT FROM true THEN RAISE EXCEPTION 'FAIL: UTF8 multibyte overflow'; END IF;
 count_pass:=count_pass+1; RAISE NOTICE 'PASS: UTF8 multibyte overflow';
 rejected:=false;
 BEGIN PERFORM public.validate_drawing_replace_input(' ',v,op); EXCEPTION WHEN SQLSTATE '22023' THEN rejected:=true; END;
 IF NOT rejected THEN RAISE EXCEPTION 'FAIL: blank symbol'; END IF;
count_pass:=count_pass+1; RAISE NOTICE 'PASS: blank symbol';
 rejected:=false;
 BEGIN PERFORM public.validate_drawing_replace_input(repeat('A',65),v,op); EXCEPTION WHEN SQLSTATE '22023' THEN rejected:=true; END;
 IF NOT rejected THEN RAISE EXCEPTION 'FAIL: symbol length65'; END IF;
count_pass:=count_pass+1; RAISE NOTICE 'PASS: symbol length65';
 rejected:=false;
 BEGIN PERFORM public.validate_drawing_replace_input('AAPL',v,NULL); EXCEPTION WHEN SQLSTATE '22023' THEN rejected:=true; END;
 IF NOT rejected THEN RAISE EXCEPTION 'FAIL: null operation'; END IF;
count_pass:=count_pass+1; RAISE NOTICE 'PASS: null operation';
 PERFORM set_config('request.jwt.claim.sub','',true); rejected:=false;
 BEGIN PERFORM public.validate_drawing_replace_input('AAPL',v,op); EXCEPTION WHEN SQLSTATE '28000' THEN rejected:=true; END;
 IF NOT rejected THEN RAISE EXCEPTION 'FAIL: anonymous'; END IF; count_pass:=count_pass+1; RAISE NOTICE 'PASS: anonymous';
 PERFORM set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',true);
 BEGIN PERFORM public.validate_drawing_replace_input('AAPL',v||v,op); DELETE FROM public.fixture_preimage; EXCEPTION WHEN SQLSTATE '22023' THEN NULL; END;
 IF (SELECT body FROM public.fixture_preimage WHERE id=1) IS DISTINCT FROM '{"preserved":true}'::jsonb THEN RAISE EXCEPTION 'FAIL: validation wrapper preimage'; END IF; count_pass:=count_pass+1; RAISE NOTICE 'PASS: validation wrapper preimage';
 candidate:=v||jsonb_set(v,'{0,id}',to_jsonb(chr(160)||'user-1'||chr(160))); rejected:=false;
 BEGIN PERFORM public.validate_drawing_replace_input('AAPL',candidate,op); EXCEPTION WHEN SQLSTATE '22023' THEN rejected:=true; END;
 IF NOT rejected THEN RAISE EXCEPTION 'FAIL: Unicode trimmed duplicate ids'; END IF; count_pass:=count_pass+1; RAISE NOTICE 'PASS: Unicode trimmed duplicate ids';
 candidate:=jsonb_set(v,'{0,points,0,t}',to_jsonb(chr(160))); rejected:=false;
 BEGIN PERFORM public.validate_drawing_replace_input('AAPL',candidate,op); EXCEPTION WHEN SQLSTATE '22023' THEN rejected:=true; END;
 IF NOT rejected THEN RAISE EXCEPTION 'FAIL: Unicode blank time'; END IF; count_pass:=count_pass+1; RAISE NOTICE 'PASS: Unicode blank time';
 rejected:=false;
 BEGIN PERFORM public.validate_drawing_replace_input(chr(160),v,op); EXCEPTION WHEN SQLSTATE '22023' THEN rejected:=true; END;
 IF NOT rejected THEN RAISE EXCEPTION 'FAIL: Unicode blank symbol'; END IF; count_pass:=count_pass+1; RAISE NOTICE 'PASS: Unicode blank symbol';
 rejected:=false;
 BEGIN PERFORM public.validate_drawing_replace_input(repeat('😀',33),v,op); EXCEPTION WHEN SQLSTATE '22023' THEN rejected:=true; END;
 IF NOT rejected THEN RAISE EXCEPTION 'FAIL: UTF16 66-unit symbol'; END IF; count_pass:=count_pass+1; RAISE NOTICE 'PASS: UTF16 66-unit symbol';
 PERFORM public.validate_drawing_replace_input(repeat('😀',32),v,op); count_pass:=count_pass+1; RAISE NOTICE 'PASS: UTF16 64-unit symbol';
 RAISE NOTICE 'ACTUAL_VALIDATION_CASES=%',count_pass;
END;
$test$;
