"""Emit the shared 2D/3D session-bar golden fixture from the CANONICAL signal engine.

The chart buckets sessions in TypeScript; the Golden Oracle buckets them in Python. The only
way those two can be held to one grid is a fixture that BOTH sides read, produced by the side
that owns the rule:

    producer  signal_layer/confluence.py::_3d_groups   (this script)
    pinned    tests/test_session_anchor.py             (Python re-derives it)
    consumed  terminal/lib/__tests__/sessionBars.test.ts (the browser must reproduce it)

The sessions are deliberately synthetic and deliberately awkward:
  * a NON-ZERO global phase — the truncated feeds start at global sessions whose index is not
    a multiple of 3, which is the case a feed-start `Math.floor(i / 3)` gets wrong;
  * three holiday gaps and every weekend — a calendar-day bucketer mis-splits on these while a
    session bucketer does not;
  * OHLCV that is distinct per session, so an aggregation bug cannot pass by coincidence.

Regenerate with:  python3 scripts/gen_session_bars_golden.py
"""
from __future__ import annotations

import datetime as dt
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from signal_layer import confluence  # noqa: E402

OUT = ROOT / "terminal" / "lib" / "__tests__" / "fixtures" / "sessionBars3D.golden.json"

# Deliberate market closures inside the window, so calendar bucketing and session bucketing
# cannot agree by accident.
HOLIDAYS = {dt.date(2019, 11, 28), dt.date(2019, 12, 25), dt.date(2020, 1, 1),
             dt.date(2020, 1, 20)}
N_SESSIONS = 120
START = dt.date(2019, 11, 1)

# Truncation points, in GLOBAL session index. 41 % 3 == 2 and 53 % 3 == 2 — a feed that starts
# mid-bar, which is the only case where the anchor changes the answer. 42 % 3 == 0 starts on a
# CLOSE session, the third residue.
TRUNCATIONS = [41, 42, 53]


def sessions() -> list[dt.date]:
    out: list[dt.date] = []
    d = START
    while len(out) < N_SESSIONS:
        if d.weekday() < 5 and d not in HOLIDAYS:
            out.append(d)
        d += dt.timedelta(days=1)
    return out


def bars(dates: list[dt.date]) -> list[list]:
    """Deterministic, strictly distinct OHLCV — one row per session."""
    rows = []
    for i, d in enumerate(dates):
        base = 100.0 + i
        rows.append([
            d.isoformat(),
            round(base, 4),                    # o
            round(base + 3 + (i % 5), 4),      # h
            round(base - 2 - (i % 3), 4),      # l
            round(base + ((i * 7) % 11) / 10, 4),  # c
            1_000 + i * 13,                    # v
        ])
    return rows


def canonical_groups(rows: list[list], mult: int, bar_anchor: int) -> list[dict]:
    """The canonical grid, taken from the engine itself for mult=3 and from the engine's own
    rule (generalised to the multiple) otherwise.

    ``_3d_groups`` hardcodes 3 because the Oracle is 3D-native. For 2D the SAME rule applies
    with `% 2`; it is re-expressed here rather than reimplemented elsewhere, and the mult=3
    branch is asserted identical to ``_3d_groups`` below so this cannot silently drift.
    """
    idx = pd.DatetimeIndex([pd.Timestamp(r[0]) for r in rows])
    close = pd.Series([float(r[4]) for r in rows], index=idx)
    n = len(rows)
    gi = np.arange(n) + int(bar_anchor)
    opens = np.empty(n, dtype=bool)
    opens[0] = True
    opens[1:] = (gi[:-1] % mult == 0)
    open_pos = np.flatnonzero(opens)
    close_pos = np.append(open_pos[1:] - 1, n - 1)

    if mult == 3:
        od, cd, px = confluence._3d_groups(close, bar_anchor)
        assert [str(t.date()) for t in od] == [rows[p][0] for p in open_pos]
        assert [str(t.date()) for t in cd] == [rows[p][0] for p in close_pos]
        assert list(px) == [float(rows[p][4]) for p in close_pos]

    out = []
    for o, c in zip(open_pos, close_pos):
        span = rows[o:c + 1]
        out.append({
            # BAR IDENTITY — TradingView's 3D bar timestamp is the bar's OPENING session.
            "time": rows[o][0],
            # DATA AVAILABILITY — the session on which the bar becomes complete. A different
            # fact from the key; the last bar of a live feed is still open on this date.
            "closeTime": rows[c][0],
            "sessions": [r[0] for r in span],
            "o": span[0][1],
            "h": max(r[2] for r in span),
            "l": min(r[3] for r in span),
            "c": span[-1][4],
            "v": sum(r[5] for r in span),
        })
    return out


def main() -> int:
    days = sessions()
    full = bars(days)

    doc = {
        "_comment": (
            "GENERATED by scripts/gen_session_bars_golden.py from signal_layer/confluence.py"
            " — do not hand-edit. The canonical 2D/3D grid: sessions grouped N at a time,"
            " phased by a global session anchor, each bar keyed by its OPENING session."
        ),
        "holidays": [d.isoformat() for d in sorted(HOLIDAYS)],
        "full": {"barAnchor": 0, "bars": full},
        "expected": {},
        "truncated": [],
    }

    for mult in (2, 3):
        doc["expected"][f"{mult}D"] = canonical_groups(full, mult, 0)

    for k in TRUNCATIONS:
        entry = {
            "dropLeading": k,
            # The published contract the browser reads: an anchor POINT, not "the first bar".
            "sessionAnchor": {"v": 1, "date": full[k][0], "index": k, "basis": "ipo"},
            "bars": full[k:],
            "expected": {},
        }
        for mult in (2, 3):
            entry["expected"][f"{mult}D"] = canonical_groups(full[k:], mult, k)
        doc["truncated"].append(entry)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(doc, indent=2) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}  "
          f"({N_SESSIONS} sessions, 3D bars={len(doc['expected']['3D'])}, "
          f"truncations={TRUNCATIONS})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
