import { describe, expect, it } from "vitest";
import { FUTURE_ANCHOR_BARS, futureBarTimes, futureCadence, futureSlotOf } from "@/lib/chart-engine/futureTime";

const dailyWeek = ["2026-08-17", "2026-08-18", "2026-08-19", "2026-08-20", "2026-08-21"];

describe("futureBarTimes", () => {
  it("continues a daily grid and skips weekends", () => {
    expect(futureBarTimes(dailyWeek, 4)).toEqual([
      "2026-08-24", "2026-08-25", "2026-08-26", "2026-08-27",
    ]);
  });

  it("keeps a weekend gap in the source from stretching the cadence", () => {
    // Fri → Mon is a 3-day jump; the median step stays one day.
    const withGap = [...dailyWeek, "2026-08-24", "2026-08-25"];
    expect(futureBarTimes(withGap, 2)).toEqual(["2026-08-26", "2026-08-27"]);
  });

  it("keeps a multi-day aggregate on its own cadence", () => {
    // A 2-day bar already spans a weekend internally; nudging off Saturday would
    // stretch the step instead of preserving it.
    const twoDay = ["2026-08-04", "2026-08-06", "2026-08-10", "2026-08-12"];
    expect(futureBarTimes(twoDay, 3)).toEqual(["2026-08-14", "2026-08-16", "2026-08-18"]);
  });

  it("spans weekends unchanged for a weekly cadence", () => {
    const weekly = ["2026-07-06", "2026-07-13", "2026-07-20", "2026-07-27"];
    expect(futureBarTimes(weekly, 2)).toEqual(["2026-08-03", "2026-08-10"]);
  });

  it("continues an intraday grid in epoch seconds", () => {
    const base = 1_756_000_000;
    const intraday = [base, base + 300, base + 600, base + 900];
    expect(futureBarTimes(intraday, 3)).toEqual([base + 1200, base + 1500, base + 1800]);
  });

  it("returns nothing when no cadence can be derived", () => {
    expect(futureBarTimes([], 5)).toEqual([]);
    expect(futureBarTimes(["2026-08-21"], 5)).toEqual([]);
    expect(futureBarTimes(dailyWeek, 0)).toEqual([]);
  });

  it("defaults to the shared anchor budget", () => {
    expect(futureBarTimes(dailyWeek)).toHaveLength(FUTURE_ANCHOR_BARS);
  });
});

describe("futureSlotOf", () => {
  const cadence = futureCadence(dailyWeek);

  it("places a time past the newest bar on its cadence slot", () => {
    // dailyWeek ends 2026-08-21; one step later is slot 0.
    expect(futureSlotOf(cadence, "2026-08-22")).toBe(0);
    expect(futureSlotOf(cadence, "2026-08-25")).toBe(3);
  });

  it("rejects times at or before the newest bar", () => {
    expect(futureSlotOf(cadence, "2026-08-21")).toBe(-1);
    expect(futureSlotOf(cadence, "2026-08-01")).toBe(-1);
  });

  it("rejects times past the anchor budget, and a series with no cadence", () => {
    expect(futureSlotOf(cadence, "2026-08-22", 2)).toBe(0);
    expect(futureSlotOf(cadence, "2026-08-30", 2)).toBe(-1);
    expect(futureSlotOf(null, "2026-08-22")).toBe(-1);
  });

  it("resolves a stored anchor whose exact grid slot no longer exists", () => {
    // A weekend date is never generated by the daily grid, but it is still a
    // future anchor and must not fall back to the live edge.
    expect(futureBarTimes(dailyWeek, 6)).not.toContain("2026-08-23");
    expect(futureSlotOf(cadence, "2026-08-23")).toBeGreaterThanOrEqual(0);
  });
});

describe("futureCadence", () => {
  it("reports the median step and its origin", () => {
    expect(futureCadence(dailyWeek)).toEqual({ stepMs: 86_400_000, lastMs: Date.parse("2026-08-21T12:00:00Z") });
  });

  it("has no cadence to report below two samples", () => {
    expect(futureCadence(["2026-08-21"])).toBeNull();
    expect(futureCadence([])).toBeNull();
  });
});
